<div class="container">
    <div class="row">
        <div class="col-12 pb-5">
            <?=replace($this->strona->tekst); ?>
        </div>
    </div>
</div>
<div id="mainboxes" class="offerbox pl-0 pl-sm-5 pr-0 pr-sm-5 pb-0">
    <div class="container-fluid p-0">
        <div class="row no-gutters">
<?php foreach($this->oferta as $o){ ?>
            <div class="col-4">
                <div class="apla d-flex align-items-center justify-content-center">
                    <div class="text-center">
                        <h3 class="m-0"><?=$this->escape($o->nazwa);?></h3>
                        <p><?=$this->escape($o->tekst);?></p>
                        <a href="<?=$this->escape($o->link);?>" class="bttn mb-0">ZOBACZ WIĘCEJ</a>
                    </div>
                </div>
                <img src="<?=$this->filesUrl();?>/oferta/<?=$this->escape($o->plik);?>" alt="<?=$this->escape($o->nazwa);?>">
            </div>
<?php } ?>
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-12 text-center"><p>GIGA może pochwalić się zdobyciem wyróżnienia przyznawanego przez Puls Biznesu dla najbardziej dynamicznych MŚP w Polsce</p></div>
        <img src="<?=$this->filesUrl();?>/upload/Gazele_Biznesu.png" alt="Gazele Biznesu" class="gazele-image">
    </div>
</div>