<div class="container">
    <div class="row">
        <div class="col-12">
            <p>GIGA Rental to inicjatywa mająca na celu budowę przestrzeni biurowych pod wynajem w najbardziej atrakcyjnych lokalizacjach. Znaczący wzrost popytu na nieruchomości pod wynajem stanowi okazję do wykorzystania zgromadzonej wiedzy i doświadczenia.</p>
            <p>&nbsp;</p>
            <p>Budowa lokali pod wynajem jest ponadto częścią większego planu Grupy GIGA mającego na celu dywersyfikację realizowanych typów inwestycji dostarczających nowych źródeł przychodów.</p>
            <p>&nbsp;</p>
            <p>W pierwszym etapie GIGA Rental będzie realizować projekty na rynku warszawskim oraz okołowarszawskim.</p>
        </div>
    </div>

    <div class="row d-flex justify-content-center pt-5 mt-4">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-10">
            <h2 class="mt-0 text-center">GIGA Rental Cieślewskich</h2>
        </div>
        <div class="col-12">
            <p>GIGA Rental Cieślewskich to koncepcja rozbudowy istniejącej siedziby firmy GIGA (budynek A) oraz wybudowania nowego biurowca o łącznej powierzchni użytkowej wynoszącej okołob <b>1 000 m<sup>2</sup></b> (budynek B)</p>
            <p>&nbsp;</p>
            <p>Wstępne koncepcje dotyczące nowego budynku <b>spotkały się z ogromnym zainteresowaniem</b> firm szukających wynajmu na okres 5-, 10-letni lub dłuższy</p>
            <p>&nbsp;</p>
            <p>Planowane rozpoczęcie budowy Rental Cieślewskich to <b>4 kwartał 2021 roku</b></p>
        </div>
        <div class="col-12 pt-5">
            <a href="<?=$this->gfxUrl();?>/giga-renta-big.png" class="swipebox"><img src="<?=$this->gfxUrl();?>/giga-rental.png" alt=""></a>
        </div>
    </div>
</div>