<div class="container">
    <div class="row">
        <div class="col-12">
            <ul class="list-unstyled">
                <li><a href="<?=$this->baseUrl;?>/">Strona główna</a>
                <li><a href="<?=$this->baseUrl;?>/o-nas/">O nas</a>
                    <ul>
                        <li><a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/">Zrównoważony rozwój</a></li>
                    </ul>
                </li>
                <li><a href="<?=$this->baseUrl;?>/misja-i-wartosci/">Misja i wartości</a></li>
                <li><a href="<?=$this->baseUrl;?>/realizacje/">Realizacje</a></li>
                <li><a href="<?=$this->baseUrl;?>/oferta/">Oferta</a>
                    <ul>
                        <li><a href="<?=$this->baseUrl;?>/oferta/giga-development/">GIGA Development</a></li>
                        <li><a href="<?=$this->baseUrl;?>/oferta/giga-rental/">GIGA Rental</a></li>
                        <li><a href="<?=$this->baseUrl;?>/oferta/giga-konsorcjum/">GIGA Konsorcjum</a></li>
                    </ul>
                </li>
                <li>
                    <a href="<?=$this->baseUrl;?>/aktualnosci/">Aktualności</a>
                    <ul>
                        <li><a href="<?=$this->baseUrl;?>/reakcja-na-covid/">Reakcja na COVID</a></li>
                    </ul>
                </li>
                <li><a href="<?=$this->baseUrl;?>/kontakt/">Kontakt</a></li>
            </ul>
        </div>
    </div>
</div>