<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-12">
            <h2 class="mt-0 text-center">Wartość firmy GIGA opiera się na optymalnym dostosowaniu struktury organizacyjnej w stosunku do skali danego projektu.</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <p>Zdolność GIGA do odpowiedniego dopasowania struktury do realizacji inwestycji stanowi o przewadze konkurencyjnej przedsiębiorstwa - wymaga ona połączenia kapitału ludzkiego oraz bezbłędnego zastosowania wypracowanych od lat procedur. Wiąże się również nierozerwalnie z postawą firmy, która od pierwszego dnia istnienia działa jako most łączący inwestorów oraz firmy budowlane. W krótkim czasie takie podejście pozwoliło firmie GIGA występować w formie generalnego wykonawcy.</p>
        </div>

        <div class="col-12 mt-5">
            <div id="animacja_1" class="container">
                <div class="row row-relative">
                    <div class="col-4 d-flex align-items-center pr-5">
                        <div class="row">
                            <div class="col-12 animate-hide animate-hide-1">
                                <div class="newproject-label"><span>1</span> Doradztwo projektowe</div>
                            </div>
                            <div class="col-12">
                                <div class="newproject animate-hide">Nowy projekt</div>
                            </div>
                            <div class="col-12 animate-hide animate-hide-1">
                                <div class="newproject-label"><span>2</span> Wybór partnerów</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row animate-hide animate-hide-2">
                            <div class="col-12">
                                <div class="step-label">
                                    <span>Branże</span>
                                    <ul>
                                        <li>Budowlana</li>
                                        <li>Sanitarna</li>
                                        <li>Elektryczna</li>
                                        <li>Chłodnicza / Wentylacyjna</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="step-label">
                                    <span>Materiały i usługi</span>
                                    <ul>
                                        <li>Konstrukcje stalowe</li>
                                        <li>Konstrukcje prefabrykowane</li>
                                        <li>Posadzki</li>
                                        <li>Rozdzielnie SN, NN</li>
                                        <li>Wentylacja / Chłodnictwo</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="step-label">
                                    <span>Organizacja</span>
                                    <ul>
                                        <li>Negocjacje z partnerami</li>
                                        <li>Ocena możliwości produkcyjnych dostawcy</li>
                                        <li>Ustalenie harmonogramu dostaw</li>
                                        <li>Wyznaczenie osób nadzorujących dostawy i ich jakość</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 d-flex align-items-center pl-5">
                        <div class="giga-konsorcjum animate-hide animate-hide-3">
                            <span>GIGA Konsorcjum</span>
                            <div class="logo-giga-konsorcjum">
                                <img src="https://giga.test/public/gfx/template/logo.png" alt="">
                            </div>
                            <div class="partnerzy-konsorcjum">
                                <img src="https://giga.test/public/gfx/template/partnerzy.jpg" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-4">
        <div class="col-12">
            <h2 class="mt-0 text-center">GIGA może podjąć się realizacji każdego przedsięwzięcia bez ograniczania się ze względu na łączną wartość lub poziom skomplikowania inwestycji – jest to możliwe dzięki wkomponowaniu pomiędzy procesy projektowania oraz wykonania również doradztwa budowlanego.</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <p>Giga od ponad 20 lat oferuje pełen zakres usług budowlanych począwszy od projektu, aż po wykończenie „pod klucz”. Obiekty wykonuje na postawie gotowej dokumentacji lub projektów własnych. Wspiera swoich Klientów w realizacji całego procesu inwestycyjnego aż po wykończenie obiektu i uzyskanie pozwolenia na użytkowanie.</p>
        </div>

        <div class="col-12 mt-5 mb-5">
            <div id="animacja_2">
                <span class="number number_1">1</span>
                <span class="number number_2">3</span>
                <span class="number number_3">2</span>

                <div class="hexagon_text hexagon_text_1">
                    <div>
                        <h4>Potrzeba</h4>
                        <p>Analiza potrzeb i wymagań projektowych</p>
                    </div>
                </div>

                <div class="hexagon_text hexagon_text_2">
                    <div>
                        <h4>Przygotowanie</h4>
                        <p>Określenie optymalnego sposobu realizacji</p>
                    </div>
                </div>

                <div class="hexagon_text hexagon_text_3">
                    <div>
                        <h4>Realizacja</h4>
                        <p>Rzetelna praca z zachowaniem zasad bezpieczeństwa</p>
                    </div>
                </div>

                <div class="hexagon_text hexagon_text_4">
                    <div>
                        <h4>Generalny Wykonawca</h4>
                    </div>
                </div>

                <div class="hexagon_tooltip hexagon_tooltip_1">
                    <h4>Współpraca z klientem</h4>
                    <p>Każdy projekt jest inny w związku z czym musi być dopasowany „na wymiar”. Chętnie dzielimy się doświadczeniem z partnerami proponując optymalne rozwiązania</p>
                </div>

                <div class="hexagon_tooltip hexagon_tooltip_2">
                    <h4>Prace przygotowawcze</h4>
                    <p>Dokładnie określamy harmonogram i wymagane nakłady. Dopasowujemy strukturę organizacyjną korzystając z wieloletniego, sprawdzonego modelu.</p>
                </div>

                <div class="hexagon_tooltip hexagon_tooltip_3">
                    <h4>Dostarczanie jakości</h4>
                    <p>Każda realizacja jest rzetelnie koordynowana, korzystając z doświadczonych inżynierów wykazujących się wysoką etyką pracy, dbających o pracowników i środowisko.</p>
                </div>
            </div>
        </div>

        <div class="col-12 mb-5">
            <p>Pracownicy GIGA pomagają Klientowi w doborze optymalnych rozwiązań materiałowych oraz konstrukcyjnych pozwalających skrócić czas realizacji, a także wskazuje rzetelnych wykonawców specjalizujących się w branżach takich jak prefabrykacja konstrukcji sprężonej lub instalacji chłodniczych. Planując daną inwestycję korzystamy ze sprawdzonej bazy firm, które są liderami rynku w swoich branżach.</p>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-4">
        <div class="col-12">
            <h2 class="mt-0 text-center">Istotną kwestią dla przedsiębiorstwa jest partnerska relacja z firmami współuczestniczącymi w realizacji projektów. Wiele spośród nich skorzystało na współpracy wymieniając się z GIGĄ zgromadzonym doświadczeniem.</h2>
        </div>
        <div class="col-8 mb-4">
            <hr>
        </div>
        <div class="col-6 pr-5 d-flex align-items-center">
            <div>
                <p>Nasza firma zawarła konsorcja z największymi przedsiębiorstwami w Polsce, takimi jak:</p>
                <ul>
                    <li>Johnson Controls (lider na rynku chłodnictwa i wentylacji przemysłowej)</li>
                    <li>Consolis (lider w produkcji prefabrykatów żelbetowych i betonu sprężonego)</li>
                </ul>
                <p>Łączenie wiedzy, doświadczenia oraz zasobów partnerów konsorcjum pozwala wykonywać realizacje na najwyższym poziomie, zabezpieczając interesy każdej ze stron.</p>
            </div>
        </div>

        <div class="col-6">
            <div style="width: 100%;height: 400px;background: #222;color:white;display: flex;justify-content: center;align-items: center">MAPA</div>
        </div>
    </div>
</div>

<script src="<?=$this->baseUrl; ?>/public/js/jquery.waypoints.min.js" charset="utf-8"></script>
<script>
    const waypoint = new Waypoint({
        element: document.getElementById('animacja_2'),
        handler: function () {
            $('.number_1, .hexagon_tooltip_1').fadeIn("slow");
            setTimeout(function () {
                $('.number_3, .hexagon_tooltip_2').fadeIn("slow");
            }, 1000);
            setTimeout(function () {
                $('.number_2, .hexagon_tooltip_3').fadeIn("slow");
            }, 2000);
        },
        offset: '70%'
    });

    $(document).ready(function(){
        const waypoint2 = new Waypoint({
            element: document.getElementById('animacja_1'),
            handler: function () {
                $('.newproject').fadeTo( "slow" , 1, function() {
                    // Animation complete.
                });
                setTimeout(function () {
                    $('.animate-hide-1').fadeTo( "slow" , 1, function() {
                        // Animation complete.
                    });
                }, 1000);
                setTimeout(function () {
                    $('.animate-hide-2').fadeTo( "slow" , 1, function() {
                        // Animation complete.
                    });
                }, 2000);
                setTimeout(function () {
                    $('.animate-hide-3').fadeTo( "slow" , 1, function() {
                        // Animation complete.
                    });
                }, 3000);
            },
            offset: '70%'
        });
    });
</script>