<div class="container">
    <div class="row d-flex justify-content-center inline">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <h2 class="mt-0 text-center" data-modaltytul="3"><?=$this->getInline($this->inline, 3, 'modaltytul');?></h2>
        </div>
        <div class="col-12 text-justify" data-modaleditortext="3">
            <?=$this->getInline($this->inline, 3, 'modaleditortext');?>
        </div>
        <?=$this->inlineModal(3, 'modaltytul,modaleditortext', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-12 mt-5">
            <div id="animacja_1" class="container">
                <div class="row row-relative">
                    <div class="col-4 d-flex align-items-center pr-5">
                        <div class="row">
                            <div class="col-12 animate-hide animate-hide-1">
                                <div class="newproject-label"><span>1</span> <?=$this->translate('tl_doradztwo_projektowe');?></div>
                            </div>
                            <div class="col-12">
                                <div class="newproject animate-hide"><?=$this->translate('tl_nowy_projekt');?><img src="<?=$this->gfxUrl();?>/bulb.png" alt="Nowy projekt"></div>
                            </div>
                            <div class="col-12 animate-hide animate-hide-1">
                                <div class="newproject-label"><span>2</span> <?=$this->translate('tl_wybor_partnerow');?></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="row animate-hide animate-hide-2">
                            <div class="col-12">
                                <div class="step-label">
                                    <span><?=$this->translate('tl_anim_label_1');?></span>
                                    <ul>
                                        <li><?=$this->translate('tl_anim_1');?></li>
                                        <li><?=$this->translate('tl_anim_2');?></li>
                                        <li><?=$this->translate('tl_anim_3');?></li>
                                        <li><?=$this->translate('tl_anim_4');?></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="step-label">
                                    <span><?=$this->translate('tl_anim_label_2');?></span>
                                    <ul>
                                        <li><?=$this->translate('tl_anim_5');?></li>
                                        <li><?=$this->translate('tl_anim_6');?></li>
                                        <li><?=$this->translate('tl_anim_7');?></li>
                                        <li><?=$this->translate('tl_anim_8');?></li>
                                        <li><?=$this->translate('tl_anim_9');?></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="step-label">
                                    <span><?=$this->translate('tl_anim_label_3');?></span>
                                    <ul>
                                        <li><?=$this->translate('tl_anim_10');?></li>
                                        <li><?=$this->translate('tl_anim_11');?></li>
                                        <li><?=$this->translate('tl_anim_12');?></li>
                                        <li><?=$this->translate('tl_anim_13');?></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4 d-flex align-items-center pl-5">
                        <div class="giga-konsorcjum animate-hide animate-hide-3">
                            <span>GIGA Construction</span>
                            <div class="logo-giga-konsorcjum">
                                <img src="<?=$this->gfxUrl();?>/logo-white.png" alt="">
                            </div>
                            <div class="partnerzy-konsorcjum">
                                <img src="<?=$this->gfxUrl();?>/partnerzy.jpg" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-4 inline">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <h2 class="mt-0 text-center" data-modaleditor="4"><?=$this->getInline($this->inline, 4, 'modaleditor');?></h2>
        </div>
        <div class="col-12 text-center" data-modaleditortext="4">
            <?=$this->getInline($this->inline, 4, 'modaleditortext');?>
        </div>
        <?=$this->inlineModal(4, 'modaleditor,modaleditortext', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row">
        <div class="col-12 mt-5 mb-5">
            <div id="animacja_2">
                <span class="number number_1">1</span>
                <span class="number number_2">3</span>
                <span class="number number_3">2</span>

                <div class="hexagon_text hexagon_text_1">
                    <div>
                        <h4><?=$this->translate('tl_hexa_label_1');?></h4>
                        <p><?=$this->translate('tl_hexa_label_2');?></p>
                    </div>
                </div>

                <div class="hexagon_text hexagon_text_2">
                    <div>
                        <h4><?=$this->translate('tl_hexa_label_3');?></h4>
                        <p><?=$this->translate('tl_hexa_label_4');?></p>
                    </div>
                </div>

                <div class="hexagon_text hexagon_text_3">
                    <div>
                        <h4><?=$this->translate('tl_hexa_label_5');?></h4>
                        <p><?=$this->translate('tl_hexa_label_6');?></p>
                    </div>
                </div>

                <div class="hexagon_text hexagon_text_4">
                    <div>
                        <h4><?=$this->translate('tl_hexa_label_7');?></h4>
                    </div>
                </div>

                <div class="hexagon_tooltip hexagon_tooltip_1">
                    <h4><?=$this->translate('tl_hexa_label_8');?></h4>
                    <p><?=$this->translate('tl_hexa_label_9');?></p>
                </div>

                <div class="hexagon_tooltip hexagon_tooltip_2">
                    <h4><?=$this->translate('tl_hexa_label_10');?></h4>
                    <p><?=$this->translate('tl_hexa_label_11');?></p>
                </div>

                <div class="hexagon_tooltip hexagon_tooltip_3">
                    <h4><?=$this->translate('tl_hexa_label_12');?></h4>
                    <p><?=$this->translate('tl_hexa_label_13');?></p>
                </div>
            </div>
        </div>

        <div class="col-12 mb-5 inline">
            <p data-modaleditor="5"><?=$this->getInline($this->inline, 5, 'modaleditor');?></p>
            <?=$this->inlineModal(5, 'modaleditor', '');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-4 inline">
        <div class="col-8 mb-4">
            <hr>
        </div>
        <div class="col-12 pb-5">
            <h2 class="mt-0 text-center" data-modaltytul="6"><?=$this->getInline($this->inline, 6, 'modaltytul');?></h2>
        </div>
        <div class="col-6 pr-5 d-flex align-items-center">
            <div data-modaleditortext="6">
                <?=$this->getInline($this->inline, 6, 'modaleditortext');?>
            </div>
        </div>

        <div class="col-6">
            <div><img src="<?=$this->filesUrl();?>/upload/mapa.jpg" alt="Mapa Polski"></div>
        </div>
        <?=$this->inlineModal(6, 'modaltytul,modaleditortext', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>
</div>

<script src="<?=$this->baseUrl; ?>/public/js/jquery.waypoints.min.js" charset="utf-8"></script>
<script>
    const waypoint = new Waypoint({
        element: document.getElementById('animacja_2'),
        handler: function () {
            $('.number_1, .hexagon_tooltip_1').fadeIn("slow");
            setTimeout(function () {
                $('.number_3, .hexagon_tooltip_2').fadeIn("slow");
            }, 1000);
            setTimeout(function () {
                $('.number_2, .hexagon_tooltip_3').fadeIn("slow");
            }, 2000);
        },
        offset: '70%'
    });

    $(document).ready(function(){
        const waypoint2 = new Waypoint({
            element: document.getElementById('animacja_1'),
            handler: function () {
                $('.newproject').fadeTo( "slow" , 1, function() {
                    // Animation complete.
                });
                setTimeout(function () {
                    $('.animate-hide-1').fadeTo( "slow" , 1, function() {
                        // Animation complete.
                    });
                }, 1000);
                setTimeout(function () {
                    $('.animate-hide-2').fadeTo( "slow" , 1, function() {
                        // Animation complete.
                    });
                }, 2000);
                setTimeout(function () {
                    $('.animate-hide-3').fadeTo( "slow" , 1, function() {
                        // Animation complete.
                    });
                }, 3000);
            },
            offset: '70%'
        });
    });
</script>