<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-12">
            <h2 class="mt-0 text-center">Wartość firmy GIGA opiera się na optymalnym dostosowaniu struktury organizacyjnej w stosunku do skali danego projektu.</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <p>Zdolność GIGA do odpowiedniego dopasowania struktury do realizacji inwestycji stanowi o przewadze konkurencyjnej przedsiębiorstwa - wymaga ona połączenia kapitału ludzkiego oraz bezbłędnego zastosowania wypracowanych od lat procedur. Wiąże się również nierozerwalnie z postawą firmy, która od pierwszego dnia istnienia działa jako most łączący inwestorów oraz firmy budowlane. W krótkim czasie takie podejście pozwoliło firmie GIGA występować w formie generalnego wykonawcy.</p>
        </div>

        <div class="col-12 mt-5 mb-5">
            <div style="width: 100%;height: 400px;background: #222;color:white;display: flex;justify-content: center;align-items: center">ANIMACJA</div>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-4">
        <div class="col-12">
            <h2 class="mt-0 text-center">GIGA może podjąć się realizacji każdego przedsięwzięcia bez ograniczania się ze względu na łączną wartość lub poziom skomplikowania inwestycji – jest to możliwe dzięki wkomponowaniu pomiędzy procesy projektowania oraz wykonania również doradztwa budowlanego.</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <p>Giga od ponad 20 lat oferuje pełen zakres usług budowlanych począwszy od projektu, aż po wykończenie „pod klucz”. Obiekty wykonuje na postawie gotowej dokumentacji lub projektów własnych. Wspiera swoich Klientów w realizacji całego procesu inwestycyjnego aż po wykończenie obiektu i uzyskanie pozwolenia na użytkowanie.</p>
        </div>

        <div class="col-12 mt-5 mb-5">
            <div style="width: 100%;height: 400px;background: #222;color:white;display: flex;justify-content: center;align-items: center">ANIMACJA</div>
        </div>

        <div class="col-12 mb-5">
            <p>Pracownicy GIGA pomagają Klientowi w doborze optymalnych rozwiązań materiałowych oraz konstrukcyjnych pozwalających skrócić czas realizacji, a także wskazuje rzetelnych wykonawców specjalizujących się w branżach takich jak prefabrykacja konstrukcji sprężonej lub instalacji chłodniczych. Planując daną inwestycję korzystamy ze sprawdzonej bazy firm, które są liderami rynku w swoich branżach.</p>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-4">
        <div class="col-12">
            <h2 class="mt-0 text-center">Istotną kwestią dla przedsiębiorstwa jest partnerska relacja z firmami współuczestniczącymi w realizacji projektów. Wiele spośród nich skorzystało na współpracy wymieniając się z GIGĄ zgromadzonym doświadczeniem.</h2>
        </div>
        <div class="col-8 mb-4">
            <hr>
        </div>
        <div class="col-6 pr-5 d-flex align-items-center">
            <div>
                <p>Nasza firma zawarła konsorcja z największymi przedsiębiorstwami w Polsce, takimi jak:</p>
                <ul>
                    <li>Johnson Controls (lider na rynku chłodnictwa i wentylacji przemysłowej)</li>
                    <li>Consolis (lider w produkcji prefabrykatów żelbetowych i betonu sprężonego)</li>
                </ul>
                <p>Łączenie wiedzy, doświadczenia oraz zasobów partnerów konsorcjum pozwala wykonywać realizacje na najwyższym poziomie, zabezpieczając interesy każdej ze stron.</p>
            </div>
        </div>

        <div class="col-6">
            <div style="width: 100%;height: 400px;background: #222;color:white;display: flex;justify-content: center;align-items: center">MAPA</div>
        </div>
    </div>
</div>