<div class="container">
	<div class="row">
		<div class="col-12 news-post">
            <article id="post-<?=$this->news->id;?>" itemscope itemType="http://schema.org/BlogPosting">
            <?php if($this->news->plik){ ?>
                <div class="news-post-img">
                    <img src="<?=$this->filesUrl();?>/news/<?=$this->news->plik;?>" alt="<?=$this->news->tytul;?>" itemprop="image">
                </div>
            <?php } ?>
                <h1 class="mt-4 mb-4"><a href="<?=$this->baseUrl;?>/aktualnosci/<?=$this->news->tag;?>/" title="<?=$this->news->tytul; ?>" itemprop="url"><span itemprop="name headline"><?=$this->news->tytul; ?></span></a></h1>
                <div itemprop="articleBody">
                    <p class="news-post-entry"><?=$this->news->wprowadzenie; ?></p>
                    <p>&nbsp;</p>
                    <?=replace($this->news->tekst); ?>
                </div>

                <meta itemprop="author" content="<?= $this->header->autor; ?>">
                <meta itemprop="datePublished" content="<?=$this->news->data;?>">
            </article>
		</div>
	</div>
</div>