<div class="title"><h1><?=$this->controlname;?><?=$this->pagename;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <ul class="nav-tabs none">
            <li><a href="<?=$this->baseUrl;?>/admin/rodo/"><span class="fa i-lista"></span>Lista klientów</a></li>
            <li><a href="<?=$this->baseUrl;?>/admin/rodo/zgody/"><span class="fa i-lista"></span>Lista regułek</a></li>
            <li><a href="<?=$this->baseUrl;?>/admin/rodo/ustawienia/"><span class="fa i-cog"></span>Ustawienia</a></li>
            <li class="active"><a href="<?=$this->baseUrl;?>/admin/rodo/logs/"><span class="fa i-lista"></span>Logi</a></li>
        </ul>
        <div class="widget">
            <div class="tab-content">
                <div class="tab-content">
                    <div class="mainForm">
                        <div class="formRow">
                            <textarea name="" id="" cols="30" rows="25" disabled><?=$this->logcontent;?></textarea>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>