<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <div class="widget">
            <div class="table-header"><form action="" id="filter-form">
                    <label>
                        <span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
                    </label>
                </form></div>
            <table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
                <thead>
                <tr>
                    <th width="80%">Nazwa</th>
                    <th width="10%"></th>
                    <?php if($this->canbetranslate){?><th width="10%"></th><?php } ?>
                </tr>
                </thead>
                <tbody class="content">
                <?php foreach($this->katalog as $p) : ?>
                    <tr>
                        <td><?=$this->escape($p->nazwa);?></td>
                        <td class="right">
                            <a href="<?=$this->baseUrl;?>/admin/boksy/edytuj/id/<?=$this->escape($p->id);?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
                            <a href="<?=$this->baseUrl;?>/admin/boksy/usun/id/<?=$this->escape($p->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
                        </td>
                        <?php if($this->canbetranslate){?>
                            <td class="right">
                                <?php foreach($this->langs as $l) { ?>
                                    <a href="<?=$this->baseUrl();?>/admin/boksy/tlumaczenie/id/<?=$this->escape($p->id);?>/lang/<?=$this->escape($l->kod);?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($l->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($l->flaga);?>"></a>
                                <?php } ?>
                            </td>
                        <?php } ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="table-footer">
                <a href="<?=$this->baseUrl;?>/admin/boksy/nowa/" class="button greyishBtn">Dodaj</a>
            </div>
        </div>
    </div>
</div>