<script type="text/javascript" language="javascript">
    //<![CDATA[
    $(document).ready(function(){
        $(".content").sortuj('<?=$this->baseUrl;?>/admin/boksy/ustaw/co/boksy/');
    });
    //]]>
</script>
<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <div class="widget">
            <div class="table-header"><form action="" id="filter-form">
                </form></div>
            <table width="100%" cellspacing="0" cellpadding="0" class="adm" id="sortable">
                <thead>
                <tr>
                    <th width="90%">Nazwa</th>
                    <th width="10%"></th>
                </tr>
                </thead>
                <tbody class="content">
                <?php foreach($this->katalog as $katalog) : ?>
                    <tr id="recordsArray_<?= $this->escape($katalog->id);?>">
                        <td><?= $this->escape($katalog->nazwa);?></td>
                        <td class="right">
                            <a href="<?= $this->baseUrl;?>/admin/boksy/edytuj/id/<?= $this->escape($katalog->id);?>/" class="actionBtn tip btnEdit" title="Edytuj" data-placement="top-right"></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>