<div class="container">
    <div class="row">
        <div class="col-12">
            <?=replace($this->strona->tekst); ?>
        </div>
    </div>

    <div class="row pt-5 mt-3">
<?php foreach($this->boksy as $b) {?>
        <div class="col-4">
            <div class="rozwoj-boks">
                <a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/<?=$b->slug;?>/"><img src="<?=$this->filesUrl();?>/boksy/<?=$b->obrazek;?>" alt="<?=$b->nazwa;?>"></a>
                <div class="rozwoj-boks-entry">
                    <h2 class="mt-0"><a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/<?=$b->slug;?>/"><?=$b->nazwa;?></a></h2>
                    <p><?=$b->wprowadzenie;?></p>
                    <a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/<?=$b->slug;?>/" class="bttn mb-0">CZYTAJ WIĘCEJ</a>
                </div>
            </div>
        </div>
<?php } ?>
    </div>
</div>