<div class="container">
    <div class="row">
        <div class="col-12">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse id iaculis tortor. Quisque eu libero vitae lacus porta auctor eu eu nibh. Integer cursus urna neque, at consequat lorem elementum vitae. Suspendisse lacinia augue eget elementum maximus. Sed sed mattis ipsum. Donec orci lacus, aliquet quis dui eget, condimentum molestie enim. Nam massa est, maximus vel luctus at, viverra sit amet ligula.</p>
        </div>
    </div>

    <div class="row pt-5 mt-3">
        <div class="col-4">
            <div class="rozwoj-boks">
                <a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/kapital-ludzki/"><img src="https://via.placeholder.com/350x400" alt=""></a>
                <div class="rozwoj-boks-entry">
                    <h2 class="mt-0"><a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/kapital-ludzki/">Kapitał Ludzki</a></h2>
                    <p>Kapitał Ludzki stanowiący o tym czym faktycznie jest GIGA, systematycznie generuje i pielęgnuje sieć powiązań z innymi przedsiębiorstwami</p>
                    <a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/kapital-ludzki/" class="bttn mb-0">CZYTAJ WIĘCEJ</a>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="rozwoj-boks">
                <a href=""><img src="https://via.placeholder.com/350x400" alt=""></a>
                <div class="rozwoj-boks-entry">
                    <h2 class="mt-0"><a href="">Odpowiedzialny rozwój</a></h2>
                    <p>Odpowiedzialny rozwój to działanie w sposób koncentrujący się na jakości wykonywanej pracy oraz ograniczaniu podziałów społecznych</p>
                    <a href="" class="bttn mb-0">CZYTAJ WIĘCEJ</a>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="rozwoj-boks">
                <a href=""><img src="https://via.placeholder.com/350x400" alt=""></a>
                <div class="rozwoj-boks-entry">
                    <h2 class="mt-0"><a href="">Ekologiczny rozwój</a></h2>
                    <p>Rozwój ekologiczny związany jest z podejmowaniem konkretnych działań, które minimalizują negatywny wpływ na środowisko</p>
                    <a href="" class="bttn mb-0">CZYTAJ WIĘCEJ</a>
                </div>
            </div>
        </div>
    </div>
</div>