<div class="container">
    <div class="row">
        <div class="col-12">
            <?=replace($this->content); ?>
        </div>
    </div>

    <div class="row pt-5 mt-3 d-flex justify-content-center">
<?php foreach($this->boksy as $key => $o) {?>
        <div class="mb-4 mb-lg-0 col-12 col-sm-6 col-lg-4" data-aos="fade-up" data-aos-delay="<?= ($key*100)+50 ;?>">
            <div class="rozwoj-boks">
                <a href="<?=$this->baseUrl;?>/<?=$this->lang;?>/zrownowazony-rozwoj/<?=$o->slug;?>/"><img src="<?=$this->filesUrl();?>/boksy/<?=$o->obrazek;?>" alt="<?php echo (isset($o->nazwa)) ? $o->nazwa : json_decode($o->json)->nazwa;?>"></a>
                <div class="rozwoj-boks-entry">
                    <h2 class="mt-0"><a href="<?=$this->baseUrl;?>/<?=$this->lang;?>/zrownowazony-rozwoj/<?=$o->slug;?>/"><?php echo (isset($o->nazwa)) ? $o->nazwa : json_decode($o->json)->nazwa;?></a></h2>
                    <p><?php echo (isset($o->wprowadzenie)) ? $o->wprowadzenie : json_decode($o->json)->wprowadzenie;?></p>
                    <a href="<?=$this->baseUrl;?>/<?=$this->lang;?>/zrownowazony-rozwoj/<?=$o->slug;?>/" class="bttn mb-0"><?=$this->translate('tl_zobacz_więcej');?></a>
                </div>
            </div>
        </div>
<?php } ?>
    </div>
</div>
<script>AOS.init();</script>