<div class="container">
    <div class="row">
        <div class="col-12">
            <?=replace($this->wpis->tekst); ?>
        </div>
    </div>

    <div class="row pt-5 mt-4">
        <?php foreach($this->boksy as $b) {?>
            <div class="mb-4 mb-lg-0 col-12 col-lg-4">
                <div class="rozwoj-boks">
                    <div class="rozwoj-boks-entry">
                        <h2 class="mt-0"><a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/<?=$b->slug;?>/"><?=$b->nazwa;?></a></h2>
                        <a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/<?=$b->slug;?>/" class="bttn mb-0">CZYTAJ WIĘCEJ</a>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>