<div class="container">
    <div class="row">
        <div class="col-12">
            <p>Firma GIGA powstała ponad 20 lat temu i nieprzerwanie świadczy usługi z zakresu budownictwa, elektryki oraz energetyki. Unikalny sposób organizacji przedsiębiorstwa skupiający się na dwóch głównych aspektach, czyli efektywności produkcji oraz elastyczności organizacyjnej, umożliwiły stabilny/organiczny rozwój.</p>
        </div>
    </div>

    <div class="row pt-5 pb-5 mt-5 mb-5">
        <div class="col-6 d-flex align-items-center pr-5">
            <p>Od pierwszego dnia istnienia GIGA posiadała szeroką kadrę inżynierską wspieraną przez doświadczone brygady budowlane. Szybko gromadzona i stale ulepszana struktura organizacyjna, a także przemyślana digitalizacja, umożliwiły realizację projektów z większym zakresem prac oraz poziomem złożoności technicznej. Firma stale rozszerzała wachlarz świadczonych usług, dzięki czemu, w niedługim czasie, stała się generalnym wykonawcą obiektów przemysłowych oraz publicznych.</p>
        </div>
        <div class="col-6">
            <div class="sliderWrapper">
                <ul>
                    <li><img src="<?=$this->filesUrl();?>/upload/slider-1.jpg" alt=""></li>
                    <li><img src="<?=$this->filesUrl();?>/upload/slider-2.jpg" alt=""></li>
                    <li><img src="<?=$this->filesUrl();?>/upload/slider-3.jpg" alt=""></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center text-center">
        <div class="col-10">
            <h2 class="mt-0">Współpraca z partnerami</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <p>GIGA od lat buduje oraz pielęgnuje sieć powiązań z firmami podwykonawczymi oraz partnerami w formie konsorcjów. O wyborze partnera budowlanego do danej realizacji decyduje jego rzetelność oraz spójność z wartościami wyznawanymi przez firmę. W portfolio przedsiębiorstw współpracujących z GIGA znajdują się zarówno duże korporacje o zasięgu europejskim, jak również firmy rodzinne działające lokalnie.</p>
        </div>
    </div>

    <div class="row mt-5 pt-5">
        <div class="col-6 pr-5 d-flex align-items-center">
            <div>
                <img src="http://marat.info.pl/img/logo.png" alt="" class="client-logo">
                <p>Jednym z wieloletnich partnerów realizacyjnych działającym na rynku polskim jest rodzinna firma budowlana „Marat”. Przedsiębiorstwo posiada nowoczesny Park Maszyn (żurawie, podnośniki itp.) pozwalający na sprawny montaż konstrukcji żelbetowych prefabrykowanych</p>
                <p>&nbsp;</p>
                <p>Swoimi doświadczeniami na temat współpracy z GIGA podzielił się Prezes firmy Pan <b>Tadeusz Marat</b>:</p>
                <p>&nbsp;</p>
                <p><i>GIGA to rzetelna firma, którą od lat wspieramy w realizacjach przemysłowych. Wyróżnia się na tle konkurencji dbałością o detale, dzięki czemu minimalizowana jest ilość elementów konstrukcyjnych, które wymagają utylizacji. Co niezwykle istotne, utrzymują ze swoimi podwykonawcami partnerskie stosunki.</i></p>
            </div>
        </div>
        <div class="col-6">
            <img src="<?=$this->filesUrl();?>/upload/marat.jpg" alt="">
        </div>
    </div>

    <div class="row d-flex justify-content-center text-center mt-5 pt-5">
        <div class="col-10">
            <h2 class="mt-0">Strategia rozwoju</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <p>Niezależnie od pozycji zajmowanej w spółce GIGA, pracownicy uczą się działać w sposób zorientowany na budowanie długotrwałego kapitału marki.​</p>
        </div>
    </div>

    <div class="row mt-5 pt-5">
        <div class="col-6 d-flex align-items-center pr-5">
            <div>
                <h3>(Bezcenny) Kapitał Ludzki</h3>
                <p>stanowiący o tym czym faktycznie jest GIGA, systematycznie / nieustannie generuje i pielęgnuje sieć powiązań z innymi przedsiębiorstwami – pracownicy GIGA wykazują się dużą elastycznością w kontakcie z firmami zewnętrznymi, preferując dogadywanie się z podwykonawcami zamiast generować konflikt. Takie postępowanie przynosi ogromne korzyści – liczne przedsiębiorstwa nieprzerwanie kontynuują współpracę z GIGA od momentu jej powstania.</p>
            </div>
        </div>
        <div class="col-6">
            <img src="<?=$this->filesUrl();?>/upload/kapital-ludzki.jpg" alt="">
        </div>
    </div>

    <div class="row flex-row-reverse mt-5 pt-5">
        <div class="col-6 d-flex align-items-center pl-5">
            <div>
                <h3>Odpowiedzialny rozwój</h3>
                <p>to działanie w sposób koncentrujący się na jakości wykonywanej pracy oraz ograniczaniu podziałów społecznych. Kadry kierownicze GIGA pracują nieustannie / wytrwale każdego dnia, aby wypracowywać pozytywne synergie wynikające z podejmowanych przedsięwzięć. Mając do dyspozycji rozbudowane narzędzia analizy makro- i mikroekonomicznej identyfikują czynniki pozytywne oraz negatywne związane z danym projektem, aby w ten sposób podejmować decyzje korzystne ekonomiczne dla spółki, rozumiejąc ich wpływ na społeczeństwo.</p>
            </div>
        </div>
        <div class="col-6">
            <img src="<?=$this->filesUrl();?>/upload/odpowiedzialny-rozwoj.jpg" alt="">
        </div>
    </div>

    <div class="row mt-5 pt-5">
        <div class="col-6 d-flex align-items-center pl-5">
            <div>
                <h3>Ekologiczny rozwój</h3>
                <p>rozwój ekologiczny związany jest z podejmowaniem konkretnych działań, które minimalizują negatywny wpływ na środowisko. Firma GIGA wyróżnia 3 główne dziedziny, które budują odpowiedzialność ekologiczną firmy. Dotyczą one ekologicznej organizacji projektu oraz placu budowy, segregacji odpadów wraz z recyklingiem, a także wyboru podwykonawców oraz uwrażliwianiu ich na ślad ekologiczny wynikający z podejmowanych działań.​</p>
            </div>
        </div>
        <div class="col-6">
            <img src="<?=$this->filesUrl();?>/upload/ekologiczny-rozwoj.jpg" alt="">
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-12 text-center">
            <p class="mb-0">Więcej informacji można uzyskać w zakładce:</p>
            <a href="" class="bttn mb-0">ZRÓWNOWAŻONY ROZWÓJ</a>
        </div>
    </div>

    <div class="row mt-5 pt-5">
        <div class="col-12">
            <blockquote>
                Jestem niezmiernie dumny z postępu jaki wykonała firma GIGA w ciągu ponad 20-letnigo istnienia. Niezwykle ważny jest dla mnie fakt, iż GIGA pozostała wierna swoim ideałom założycielskim, które opierają się na rozwoju pracowników oraz długotrwałym budowaniu marki. Na każdym kroku spotykam ludzi, którzy wykazują się odpowiedzialną postawą w życiu zawodowym oraz prywatnym – jest to sukces związany z pozytywnym wpływem kultury organizacyjnej wytworzonej i stale kreowanej (wykreowanej) wewnątrz naszej firmy.
            </blockquote>
            <div class="blockquote-person text-center">
                <img src="https://www.internationalpublishers.org/templates/it_headlines/custom/images/about-ipa/committee-members/Roberto-Banchik-Square-crop.jpg" alt="">
                <h3>Robert Dąbrowski</h3>
                <p class="mb-3"><i>Prezes Zarządu</i></p>
                <p class="small">Absolwent Wydziału Elektrycznego Politechniki Warszawskiej o specjalności Maszyny Elektryczne</p>
                <p class="small">MBA na Koźmiński Business School</p>
            </div>

        </div>

    </div>
</div>