<div class="container">
    <div class="row inline">
        <div class="col-12 text-justify">
            <h4 data-modaleditor="12"><?=$this->getInline($this->inline, 12, 'modaleditor');?></h4>
        </div>
        <?=$this->inlineModal(12, 'modaleditor', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row pt-3 pb-5 mt-0 mt-lg-5 mb-5">
        <div class="col-12 col-lg-6 d-flex align-items-center pr-5 text-justify inline">
            <p data-modaleditor="13"><?=$this->getInline($this->inline, 13, 'modaleditor');?></p>
            <?=$this->inlineModal(13, 'modaleditor', '');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
        <div class="col-12 col-lg-6 mt-5 mt-lg-0">
            <div class="sliderWrapper image-border">
                <ul>
                <?php foreach($this->slider as $s) {?>
                    <li><img src="<?=$this->filesUrl();?>/galeria/big/<?=$s->plik;?>" alt="Firma GIGA"></li>
                <?php } ?>
                </ul>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center text-center inline">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12 col-lg-10">
            <h2 class="mt-0" data-modaltytul="14"><?=$this->getInline($this->inline, 14, 'modaltytul');?></h2>
        </div>
        <div class="col-12 text-justify">
            <p data-modaleditor="14"><?=$this->getInline($this->inline, 14, 'modaleditor');?></p>
        </div>
        <?=$this->inlineModal(14, 'modaltytul,modaleditor', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row mt-0 mt-lg-5 pt-5 inline">
        <div class="col-12 col-lg-6 pr-5 d-flex align-items-center" data-aos="fade-right" data-aos-offset="350">
            <div class="text-justify" data-modaleditortext="22"><?=$this->getInline($this->inline, 22, 'modaleditortext');?></div>
        </div>
        <div class="col-12 col-lg-6 mt-5 mt-lg-0" data-aos="fade-left" data-aos-offset="350">
            <img src="<?=$this->getInline($this->inline, 22, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 22, 'obrazek_alt');?>" data-img="22" class="image-border">
        </div>
        <?=$this->inlineModal(22, 'modaleditortext,obrazek,obrazek_alt', '540,660');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row d-flex justify-content-center text-center mt-0 mt-lg-5 pt-5 inline">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12 col-lg-10">
            <h2 class="mt-0" data-modaltytul="15"><?=$this->getInline($this->inline, 15, 'modaltytul');?></h2>
        </div>
        <div class="col-12">
            <p data-modaleditor="15"><?=$this->getInline($this->inline, 15, 'modaleditor');?></p>
        </div>
        <?=$this->inlineModal(15, 'modaltytul,modaleditor', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row mt-0 mt-lg-5 pt-3 pt-lg-5 inline">
        <div class="col-12 col-lg-6 d-flex align-items-center pr-3 pr-lg-5" data-aos="fade-right" data-aos-offset="350">
            <div>
                <h3 data-modaltytul="16"><?=$this->getInline($this->inline, 16, 'modaltytul');?></h3>
                <div data-modaleditortext="16"><?=$this->getInline($this->inline, 16, 'modaleditortext');?></div>
            </div>
        </div>
        <div class="col-12 col-lg-6 mt-5 mt-lg-0" data-aos="fade-left" data-aos-offset="350">
            <img src="<?=$this->getInline($this->inline, 16, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 16, 'obrazek_alt');?>" data-img="16" class="image-border">
        </div>
        <?=$this->inlineModal(16, 'modaltytul,modaleditortext,obrazek,obrazek_alt', '540,420');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row flex-row-reverse mt-0 mt-lg-5 pt-0 pt-lg-5 inline">
        <div class="col-12 col-lg-6 d-flex align-items-center pl-3 pl-lg-5" data-aos="fade-right" data-aos-offset="350">
            <div>
                <h3 data-modaltytul="17"><?=$this->getInline($this->inline, 17, 'modaltytul');?></h3>
                <div data-modaleditortext="17"><?=$this->getInline($this->inline, 17, 'modaleditortext');?></div>
            </div>
        </div>
        <div class="col-12 col-lg-6 mt-5 mt-lg-0" data-aos="fade-left" data-aos-offset="350">
            <img src="<?=$this->getInline($this->inline, 17, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 17, 'obrazek_alt');?>" data-img="17" class="image-border">
        </div>
        <?=$this->inlineModal(17, 'modaltytul,modaleditortext,obrazek,obrazek_alt', '540,420');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row mt-0 mt-lg-5 pt-0 pt-lg-5 inline">
        <div class="col-12 col-lg-6 d-flex align-items-center pr-3 pr-lg-5" data-aos="fade-right" data-aos-offset="350">
            <div>
                <h3 data-modaltytul="18"><?=$this->getInline($this->inline, 18, 'modaltytul');?></h3>
                <div data-modaleditortext="18"><?=$this->getInline($this->inline, 18, 'modaleditortext');?></div>
            </div>
        </div>
        <div class="col-12 col-lg-6 mt-5 mt-lg-0" data-aos="fade-left" data-aos-offset="350">
            <img src="<?=$this->getInline($this->inline, 18, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 18, 'obrazek_alt');?>" data-img="18" class="image-border">
        </div>
        <?=$this->inlineModal(18, 'modaltytul,modaleditortext,obrazek,obrazek_alt', '540,420');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row mt-0 mt-lg-5">
        <div class="col-12 text-center">
            <p class="mb-0"><?=$this->translate('tl_wiecej_informacji');?></p>
            <a href="<?=$this->baseUrl;?>/<?=$this->lang;?>/zrownowazony-rozwoj/" class="bttn mb-0"><?=$this->translate('tl_zrownowazony_rozwoj');?></a>
        </div>
    </div>
</div>
<div id="carousel" class="container mt-0 mt-lg-5 pt-5">
    <?php foreach($this->opinie as $o){?>
        <div class="row">
            <div class="col-12">
                <blockquote><?php echo (isset($o->tekst)) ? $o->tekst : json_decode($o->json)->tekst;?></blockquote>
                <div class="blockquote-person text-center">
                    <?php if($o->plik) {?><img src="<?=$this->baseUrl;?>/files/opinie/<?=$this->escape($o->plik);?>" alt="<?php echo (isset($o->imie)) ? $o->imie : json_decode($o->json)->imie;?> - <?php echo (isset($o->stanowisko)) ? $o->stanowisko : json_decode($o->json)->stanowisko;?>"><?php } ?>
                    <h3><?php echo (isset($o->imie)) ? $o->imie : json_decode($o->json)->imie;?></h3>
                    <p class="mb-3"><i><?php echo (isset($o->stanowisko)) ? $o->stanowisko : json_decode($o->json)->stanowisko;?></i></p>
                    <p class="small"><?php echo (isset($o->dodatkowe)) ? $o->dodatkowe : json_decode($o->json)->dodatkowe;?></p>
                </div>
            </div>
        </div>
    <?php } ?>
</div>
<script type="text/javascript">
    AOS.init();
    $(document).ready(function(){
        $('#carousel').slick();
    });
</script>