<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <div class="widget">
            <div class="table-header"><form action="" id="filter-form">
                    <label>
                        <span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
                    </label>
                </form></div>
            <table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
                <thead>
                <tr>
                    <th width="20%">Imie</th>
                    <th width="20%">Stanowisko</th>
                    <th width="20%">Miejsce</th>
                    <th width="20%">Zdjęcie</th>
                    <th width="10%"></th>
                </tr>
                </thead>
                <tbody class="content">
                <?php foreach($this->katalog as $p) : ?>
                    <tr id="recordsArray_<?= $this->escape($p->id);?>">
                        <td><?=$this->escape($p->imie);?></td>
                        <td><?=$this->escape($p->stanowisko);?></td>
                        <td><?php echo ($p->place_id == 1) ? 'Misja i wartości':'O nas';?></td>
                        <td><?php if($p->plik){?><img src="<?=$this->baseUrl;?>/files/opinie/<?=$this->escape($p->plik);?>" alt="<?=$this->escape($p->imie);?>" style="width: 90px"><?php } ?></td>
                        <td class="right">
                            <a href="<?=$this->baseUrl;?>/admin/opinie/edytuj/id/<?=$this->escape($p->id);?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
                            <a href="<?=$this->baseUrl;?>/admin/opinie/usun/id/<?=$this->escape($p->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="table-footer">
                <a href="<?=$this->baseUrl;?>/admin/opinie/nowa/" class="button greyishBtn">Dodaj</a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    $(document).ready(function(){
        $(".content").sortuj('<?=$this->baseUrl;?>/admin/opinie/ustaw/co/opinie/');
    });
    //]]>
</script>