<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <div class="widget">
            <div class="table-header"><form action="" id="filter-form">
                    <label>
                        <span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
                    </label>
                </form></div>
            <table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
                <thead>
                <tr>
                    <th width="90%">Nazwa</th>
                    <th width="10%"></th>
                </tr>
                </thead>
                <tbody class="content">
                <?php foreach($this->lista as $news) : ?>
                    <tr>
                        <td><?=$this->escape($news->nazwa);?></td>
                        <td class="right">
                            <a href="<?=$this->baseUrl;?>/admin/realizacje/edytuj/id/<?=$this->escape($news->id);?>/" class="actionBtn tip btnEdit" title="Edytuj wpis"></a>
                            <a href="<?=$this->baseUrl;?>/admin/realizacje/usun/id/<?=$this->escape($news->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń wpis"></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="table-footer">
                <a href="<?=$this->baseUrl;?>/admin/realizacje/nowa/" class="button greyishBtn">Dodaj wpis</a>
            </div>
        </div>
    </div>
</div>