<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-10">
            <h2 class="mt-0 text-center">Misja</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <p>Firma GIGA powstała w celu budowania obiektów dla instytucji publicznych oraz firm prywatnych z zachowaniem szczególnej troski o jakość wykonania oraz poszanowaniem środowiska naturalnego. Każdy członek spółki GIGA, poczynając od inżynierów oraz analityków, a kończąc na dyrektorach oraz zarządzie, dostrzega, że budowanie jest czymś więcej niż tylko zagadnieniem konstrukcyjno-inżynierskim.</p>
        </div>
    </div>

    <div class="row pt-5">
        <div class="col-6 d-flex align-items-center pr-5">
            <div>
                <p>Budownictwo polega nie tylko na wznoszeniu nowych konstrukcji, budowanie to także dążenie do osiągania trwałych oraz wartościowych relacji międzyludzkich pomagających tworzyć lepsze jutro</p>
            </div>
        </div>
        <div class="col-6">
            <img src="<?=$this->filesUrl();?>/upload/misja-1.jpg" alt="">
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-5">
        <div class="col-10">
            <h2 class="mt-0 text-center">Wizja</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12">
            <p>GIGA od początku swojego istnienia dąży do wyznaczania trendów w dwóch głównych dziedzinach – <b>efektywności produkcji</b> oraz <b>rozwoju (wszechstronności) pracowników</b></p>
        </div>
    </div>

    <div class="row flex-row-reverse mt-5">
        <div class="col-6 d-flex align-items-center pl-5">
            <div>
                <p>Efektywność produkcji rozumiemy jako stałe prace badawcze w zakresie optymalnego użycia materiałów a także minimalizacji odpadów powstających na budowie. Takie odpowiedzialne zarządzanie surowcami pomaga chronić środowisko naturalne. Jest to również optymalizacja operacyjna pozwalająca osiągać lepszą terminowość oraz stale podwyższać jakość realizacji.</p>
            </div>
        </div>
        <div class="col-6">
            <img src="<?=$this->filesUrl();?>/upload/misja-2.jpg" alt="">
        </div>
    </div>

    <div class="row mt-5 pt-4">
        <div class="col-6 d-flex align-items-center pr-5">
            <div>
                <p>Nasze przedsiębiorstwo dokłada ogromnych starań, aby stworzyć miejsce do pracy, z którym każdy pracownik będzie się utożsamiać i w którym w pełni wykorzysta swoje zdolności. Tworzymy warunki do poszerzania horyzontów naszych podopiecznych, dzięki ciągłemu wsłuchiwaniu się w ich potrzeby. Pozwalamy im rozwijać się w różnych dziedzinach oraz podwyższać ich kompetencje. Takie działanie pozwala uelastyczniać organizację na wypadek nieprzewidzianych zdarzeń.</p>
            </div>
        </div>
        <div class="col-6">
            <img src="<?=$this->filesUrl();?>/upload/misja-3.jpg" alt="">
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-5">
        <div class="col-12">
            <h2 class="mt-0 mb-5">System wartości:</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <h3>Solidność</h3>
        </div>
        <div class="col-8">
            <p>Stabilna konstrukcja musi opierać się na solidnym fundamencie. W naszej firmie to przejrzyste zasady działania pozwalają nam osiągać wysoką jakość. Zespół GIGA od lat udowadnia swoją rzetelność, która motywuje inne firmy do naśladowania dobrych praktyk.</p>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <h3>Kreatywność</h3>
        </div>
        <div class="col-8">
            <p>Doceniamy osoby, które wykazują inicjatywę i pragną stale się doskonalić. Każdy pracownik może swoim działaniem pomóc organizacji, ponieważ strategiczne decyzje są równie ważne co bieżące działania. Wierzymy, że każdy pracownik może stać się promotorem zmiany na lepsze.</p>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <h3>Odpowiedzialność</h3>
        </div>
        <div class="col-8">
            <p>Każdy z nas z pasją wykonuje powierzone zadania, bo wszyscy dążymy do wspólnego celu. Jesteśmy uważni na pracę naszych współpracowników i gotowi do działania, gdy można pomóc całemu zespołowi. Podejmujemy decyzje z troską o środowisko naturalne, kierując się zasadą - „Przyszłe pokolenia powinny zastać Ziemię w takim samym lub lepszym stanie”.</p>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-5">
        <div class="col-10">
            <h2 class="mt-0 text-center">Jak nasze dążenia są realizowane?</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <blockquote>Dzięki ciągłej wymianie doświadczeń pomiędzy pracownikami administracyjnymi z inżynierami oraz niezbędnym szkoleniom, absencja dyrektora biura na budowie nie paraliżuje przepływu informacji pomiędzy budową a siedzibą zarządu GIGA. Każdy młody inżynier szkoli się w wybranych aspektach prowadzenia administracji, w związku z czym jest on w stanie skutecznie zastąpić pracownika w razie nieprzewidzianej nieobecności.</blockquote>
            <div class="blockquote-person text-center">
                <img src="https://www.internationalpublishers.org/templates/it_headlines/custom/images/about-ipa/committee-members/Roberto-Banchik-Square-crop.jpg" alt="">
                <h3>Jakub</h3>
                <p class="mb-3"><i>Młodszy inżynier</i></p>
            </div>

        </div>
    </div>
</div>