<div class="container">
    <div class="row d-flex justify-content-center inline">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-10">
            <h2 class="mt-0 text-center" data-modaltytul="7"><?=$this->getInline($this->inline, 7, 'modaltytul');?></h2>
        </div>
        <div class="col-12 text-justify" data-modaleditortext="7">
            <?=$this->getInline($this->inline, 7, 'modaleditortext');?>
        </div>
        <?=$this->inlineModal(7, 'modaltytul,modaleditortext', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="pt-5">
        <div class="row inline">
            <div class="col-6 d-flex align-items-center pr-5">
                <div class="text-justify" data-modaleditortext="9">
                    <?=$this->getInline($this->inline, 9, 'modaleditortext');?>
                </div>
            </div>
            <div class="col-6">
                <img src="<?=$this->getInline($this->inline, 9, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 9, 'obrazek_alt');?>" data-img="9" class="image-border">
            </div>
            <?=$this->inlineModal(9, 'modaleditortext,obrazek,obrazek_alt', '540,420');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-5 inline">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-10">
            <h2 class="mt-0 text-center" data-modaltytul="8"><?=$this->getInline($this->inline, 8, 'modaltytul');?></h2>
        </div>
        <div class="col-12 text-justify" data-modaleditortext="8">
            <?=$this->getInline($this->inline, 8, 'modaleditortext');?>
        </div>
        <?=$this->inlineModal(8, 'modaltytul,modaleditortext', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row flex-row-reverse mt-5 inline">
        <div class="col-6 d-flex align-items-center pl-5" data-aos="fade-left" data-aos-offset="350">
            <div class="text-justify" data-modaleditortext="10">
                <?=$this->getInline($this->inline, 10, 'modaleditortext');?>
            </div>
        </div>
        <div class="col-6" data-aos="fade-right" data-aos-offset="350">
            <img src="<?=$this->getInline($this->inline, 10, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 10, 'obrazek_alt');?>" data-img="10" class="image-border">
        </div>
        <?=$this->inlineModal(10, 'modaleditortext,obrazek,obrazek_alt', '540,420');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="mt-5 pt-4">
        <div class="row inline">
            <div class="col-6 d-flex align-items-center pr-5" data-aos="fade-left" data-aos-offset="350">
                <div class="text-justify" data-modaleditortext="11">
                    <?=$this->getInline($this->inline, 11, 'modaleditortext');?>
                </div>
            </div>
            <div class="col-6" data-aos="fade-right" data-aos-offset="350">
                <img src="<?=$this->getInline($this->inline, 11, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 11, 'obrazek_alt');?>" data-img="11" class="image-border">
            </div>
            <?=$this->inlineModal(11, 'modaleditortext,obrazek,obrazek_alt', '540,420');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-5">
        <div class="col-12">
            <h2 class="mt-0 mb-5">System wartości:</h2>
        </div>
    </div>
    <div class="row" data-aos="fade-up" data-aos-offset="300">
        <div class="col-2">
            <div class="misja-icon">
                <img src="<?=$this->gfxUrl();?>/solidnosc-icon.png" alt="Solidność">
            </div>
        </div>
        <div class="col-10 text-justify d-flex align-items-center">
            <div>
                <h3 class="mt-0 mb-2">Solidność</h3>
                <p>Stabilna konstrukcja musi opierać się na solidnym fundamencie. W naszej firmie to przejrzyste zasady działania pozwalają nam osiągać wysoką jakość. Zespół GIGA od lat udowadnia swoją rzetelność, która motywuje inne firmy do naśladowania dobrych praktyk.</p>
            </div>
        </div>
    </div>
    <div class="row mt-4" data-aos="fade-up" data-aos-offset="300">
        <div class="col-12">
            <hr>
        </div>
    </div>
    <div class="row" data-aos="fade-up" data-aos-offset="300">
        <div class="col-2">
            <div class="misja-icon">
                <img src="<?=$this->gfxUrl();?>/kreatywnosc-icon.png" alt="Kreatywność">
            </div>
        </div>
        <div class="col-10 text-justify d-flex align-items-center">
            <div>
                <h3 class="mt-0 mb-2">Kreatywność</h3>
                <p>Doceniamy osoby, które wykazują inicjatywę i pragną stale się doskonalić. Każdy pracownik może swoim działaniem pomóc organizacji, ponieważ strategiczne decyzje są równie ważne co bieżące działania. Wierzymy, że każdy pracownik może stać się promotorem zmiany na lepsze.</p>
            </div>
        </div>
    </div>
    <div class="row mt-4" data-aos="fade-up" data-aos-offset="300">
        <div class="col-12">
            <hr>
        </div>
    </div>
    <div class="row" data-aos="fade-up" data-aos-offset="300">
        <div class="col-2">
            <div class="misja-icon">
                <img src="<?=$this->gfxUrl();?>/odpowiedzialnosc-icon.png" alt="Odpowiedzialność">
            </div>
        </div>
        <div class="col-10 text-justify d-flex align-items-center">
            <div>
                <h3 class="mt-0 mb-2">Odpowiedzialność</h3>
                <p>Każdy z nas z pasją wykonuje powierzone zadania, bo wszyscy dążymy do wspólnego celu. Jesteśmy uważni na pracę naszych współpracowników i gotowi do działania, gdy można pomóc całemu zespołowi. Podejmujemy decyzje z troską o środowisko naturalne, kierując się zasadą - „Przyszłe pokolenia powinny zastać Ziemię w takim samym lub lepszym stanie”.</p>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-5">
        <div class="col-10">
            <h2 class="mt-0 text-center">Jak nasze dążenia są realizowane?</h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
    </div>
</div>
<div id="carousel" class="container">
    <div class="row">
        <div class="col-12">
            <blockquote>Każdy inżynier aktywnie uczestniczy we wszystkich aspektach procesu inwestycyjnego, w tym rozliczenia robót i prognozy kosztów do momentu zakończenia inwestycji. Wspomaga w ten sposób dział rozliczenia produkcji, który nie zawsze ma bezpośredni i w związku z tym miarodajny wgląd do sytuacji na placu budowy.</blockquote>
            <div class="blockquote-person text-center">
                <img src="https://www.internationalpublishers.org/templates/it_headlines/custom/images/about-ipa/committee-members/Roberto-Banchik-Square-crop.jpg" alt="">
                <h3>Jakub</h3>
                <p class="mb-3"><i>Młodszy inżynier</i></p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <blockquote>Utrzymujemy poziom komunikacji zespołów z centrali i budów na najwyższym poziomie. Centrala firmy otrzymuje od Kierowników budów, wyczerpujący opis zaawansowania robót wraz z planowanymi kolejnymi działaniami, w związku z czym jest w stanie wygenerować raporty o wysokiej jakości informacyjnej dla zarządu. Dodatkowo cotygodniowe koordynacje zespołów z biura i budowy,  pozwalaj tworzyć dokumenty o odpowiednim zbilansowaniu techniczno-użytkowym.</blockquote>
            <div class="blockquote-person text-center">
                <img src="https://images.generated.photos/JN_VTgcC2WllGU94Ow99d-hjMb3ZAdUPlq_iHRc4lV0/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAyNzM4MTguanBn.jpg" alt="">
                <h3>Magdalena</h3>
                <p class="mb-3"><i>Kierownik biura GIGA</i></p>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    AOS.init();
    $(document).ready(function(){
        $('#carousel').slick();
    });
</script>