<div class="container">
    <div class="row d-flex justify-content-center inline">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12 col-lg-10">
            <h2 class="mt-0 text-center" data-modaltytul="7"><?=$this->getInline($this->inline, 7, 'modaltytul');?></h2>
        </div>
        <div class="col-12 text-justify" data-modaleditortext="7">
            <?=$this->getInline($this->inline, 7, 'modaleditortext');?>
        </div>
        <?=$this->inlineModal(7, 'modaltytul,modaleditortext', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="pt-5">
        <div class="row inline">
            <div class="col-12 col-lg-6 d-flex align-items-center pr-5">
                <div class="text-justify" data-modaleditortext="9">
                    <?=$this->getInline($this->inline, 9, 'modaleditortext');?>
                </div>
            </div>
            <div class="col-12 col-lg-6 mt-5 mt-lg-0">
                <img src="<?=$this->getInline($this->inline, 9, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 9, 'obrazek_alt');?>" data-img="9" class="image-border">
            </div>
            <?=$this->inlineModal(9, 'modaleditortext,obrazek,obrazek_alt', '540,420');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-0 mt-lg-5 pt-5 inline">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12 col-lg-10">
            <h2 class="mt-0 text-center" data-modaltytul="8"><?=$this->getInline($this->inline, 8, 'modaltytul');?></h2>
        </div>
        <div class="col-12 text-justify" data-modaleditortext="8">
            <?=$this->getInline($this->inline, 8, 'modaleditortext');?>
        </div>
        <?=$this->inlineModal(8, 'modaltytul,modaleditortext', '');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row flex-row-reverse mt-5 inline">
        <div class="col-12 col-lg-6 d-flex align-items-center pl-3 pl-lg-5" data-aos="fade-left" data-aos-offset="350">
            <div class="text-justify" data-modaleditortext="10">
                <?=$this->getInline($this->inline, 10, 'modaleditortext');?>
            </div>
        </div>
        <div class="col-12 col-lg-6 mt-5 mt-lg-0" data-aos="fade-right" data-aos-offset="350">
            <img src="<?=$this->getInline($this->inline, 10, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 10, 'obrazek_alt');?>" data-img="10" class="image-border">
        </div>
        <?=$this->inlineModal(10, 'modaleditortext,obrazek,obrazek_alt', '540,420');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="mt-0 mt-lg-5 pt-4">
        <div class="row inline">
            <div class="col-12 col-lg-6 d-flex align-items-center pr-5" data-aos="fade-left" data-aos-offset="350">
                <div class="text-justify" data-modaleditortext="11">
                    <?=$this->getInline($this->inline, 11, 'modaleditortext');?>
                </div>
            </div>
            <div class="col-12 col-lg-6 mt-5 mt-lg-0" data-aos="fade-right" data-aos-offset="350">
                <img src="<?=$this->getInline($this->inline, 11, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 11, 'obrazek_alt');?>" data-img="11" class="image-border">
            </div>
            <?=$this->inlineModal(11, 'modaleditortext,obrazek,obrazek_alt', '540,420');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-0 mt-lg-5 pt-5">
        <div class="col-12">
            <h2 class="mt-0 mb-5"><?=$this->translate('tl_system_wartosci');?>:</h2>
        </div>
    </div>

    <div class="row inline" data-aos="fade-up" data-aos-offset="300">
        <div class="col-12 col-md-2">
            <div class="misja-icon">
                <img src="<?=$this->getInline($this->inline, 19, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 19, 'obrazek_alt');?>" data-img="19">
            </div>
        </div>
        <div class="col-12 col-md-10 text-justify d-flex align-items-center">
            <div>
                <h3 class="mt-0 mb-2" data-modaltytul="19"><?=$this->getInline($this->inline, 19, 'modaltytul');?></h3>
                <p data-modaleditor="19"><?=$this->getInline($this->inline, 19, 'modaleditor');?></p>
            </div>
        </div>
        <?=$this->inlineModal(19, 'modaltytul,modaleditor,obrazek,obrazek_alt', '120,120');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row mt-4" data-aos="fade-up" data-aos-offset="300">
        <div class="col-12">
            <hr>
        </div>
    </div>

    <div class="row inline" data-aos="fade-up" data-aos-offset="300">
        <div class="col-12 col-md-2">
            <div class="misja-icon">
                <img src="<?=$this->getInline($this->inline, 20, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 20, 'obrazek_alt');?>" data-img="20">
            </div>
        </div>
        <div class="col-12 col-md-10 text-justify d-flex align-items-center">
            <div>
                <h3 class="mt-0 mb-2" data-modaltytul="20"><?=$this->getInline($this->inline, 20, 'modaltytul');?></h3>
                <p data-modaleditor="20"><?=$this->getInline($this->inline, 20, 'modaleditor');?></p>
            </div>
        </div>
        <?=$this->inlineModal(20, 'modaltytul,modaleditor,obrazek,obrazek_alt', '120,120');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row mt-4" data-aos="fade-up" data-aos-offset="300">
        <div class="col-12">
            <hr>
        </div>
    </div>

    <div class="row inline" data-aos="fade-up" data-aos-offset="300">
        <div class="col-12 col-md-2">
            <div class="misja-icon">
                <img src="<?=$this->getInline($this->inline, 21, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 21, 'obrazek_alt');?>" data-img="21">
            </div>
        </div>
        <div class="col-12 col-md-10 text-justify d-flex align-items-center">
            <div>
                <h3 class="mt-0 mb-2" data-modaltytul="21"><?=$this->getInline($this->inline, 21, 'modaltytul');?></h3>
                <p data-modaleditor="21"><?=$this->getInline($this->inline, 21, 'modaleditor');?></p>
            </div>
        </div>
        <?=$this->inlineModal(21, 'modaltytul,modaleditor,obrazek,obrazek_alt', '120,120');?>
        <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
    </div>

    <div class="row d-flex justify-content-center mt-5 pt-5">
        <div class="col-12 col-lg-10">
            <h2 class="mt-0 text-center"><?=$this->translate('tl_nasze_dazenia');?></h2>
        </div>
        <div class="col-8">
            <hr>
        </div>
    </div>
</div>
<div id="carousel" class="container">
<?php foreach($this->opinie as $o){?>
    <div class="row">
        <div class="col-12">
            <blockquote><?php echo (isset($o->tekst)) ? $o->tekst : json_decode($o->json)->tekst;?></blockquote>
            <div class="blockquote-person text-center">
                <?php if($o->plik) {?><img src="<?=$this->baseUrl;?>/files/opinie/<?=$this->escape($o->plik);?>" alt="<?php echo (isset($o->imie)) ? $o->imie : json_decode($o->json)->imie;?> - <?php echo (isset($o->stanowisko)) ? $o->stanowisko : json_decode($o->json)->stanowisko;?>"><?php } ?>
                <h3><?php echo (isset($o->imie)) ? $o->imie : json_decode($o->json)->imie;?></h3>
                <p class="mb-3"><i><?php echo (isset($o->stanowisko)) ? $o->stanowisko : json_decode($o->json)->stanowisko;?></i></p>
            </div>
        </div>
    </div>
<?php } ?>
</div>
<script type="text/javascript">
    AOS.init();
    $(document).ready(function(){
        $('#carousel').slick();
    });
</script>