<div class="container">
    <div class="row d-flex justify-content-center text-center">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-10 mb-5">
            <?=replace($this->strona->tekst); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="row">
                <div class="col-12">
                    <div class="covid-text ctl-1">
                        <p>Regularna dezynfekcja pomieszczeń biurowych (co 1,5 godziny) przez wyznaczoną i przeszkoloną osobę (w szczególności blatów, klamek, uchwytów)</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-2">
                        <p>Wyznaczenie osób monitorujących stan zapasów środków dezynfekujących w przestrzeniach wspólnych oraz mydeł w płynie w łazienkach.</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-3">
                        <p>Udostępnienie maseczek ochronnych dla wszystkich pracowników firmy GIGA oraz, w razie potrzeby, dla współpracujących z nimi podwykonawców / brygad</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-4">
                        <p>Prowadzenie porannego wywiadu na budowie z osobami wchodzącymi na teren inwestycji w celu oceny stanu zdrowia</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 d-flex align-items-center">
            <div class="covid-circle">
                Kontakty międzyludzkie oraz higiena
            </div>
        </div>
        <div class="col-4">
            <div class="row">
                <div class="col-12">
                    <div class="covid-text ctr-1">
                        <p>Zapisywanie listy osób wchodzących oraz schodzących z terenu budowy w celu szybkiej reakcji na potencjalne pojawienie się przypadku Covid-19 wśród pracowników.</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-2">
                        <p>Zachowanie odległości 1,5m na spotkaniach koordynacyjnych oraz wietrzenie pomieszczeń po każdym spotkaniu / co 1,5 godziny.</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-3">
                        <p>Odstawianie paczek otrzymanych pocztą na 48 godzin lub w przypadku dokumentów pilnych, pełna dezynfekcja opakowań przez otwarciem.</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-4">
                        <p>Regularnie pranie ubrań roboczych w wysokich temperaturach. Udostępnienie dla robotników detergentów do prania ubrań, gdy są przekazywane dla innych osób.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 pt-5 pb-5 mt-4 mb-3">
            <img src="<?=$this->gfxUrl();?>/covid.png" alt="Reakcja na COVID">
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="row">
                <div class="col-12">
                    <div class="covid-text ctl-1">
                        <p>Stworzenie warunków do pracy zdalnej dla osób, które mogą realizować swoje zadania na odległość</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-2">
                        <p>Zapewnienie większej ilości kontenerów oraz pomieszczeń na budowach w celu zmniejszenia rotacji osób w zamkniętych przestrzeniach</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-3">
                        <p>Optymalizacja liczby fizycznych kontaktów z dostawcami materiałów na budowę w celu ograniczenia ryzyka rozprzestrzenienia wirusa (planowanie większych dostaw</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-4">
                        <p>Pracownicy są zachęcani, aby zabierać ze sobą laptopy, myszki i innych urządzenia osobiste po zakończeniu pracy.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 d-flex align-items-center">
            <div class="covid-circle">
                Rozwiązania organizacyjne
            </div>
        </div>
        <div class="col-4">
            <div class="row">
                <div class="col-12">
                    <div class="covid-text ctr-1">
                        <p>Ograniczenie liczby osób przewożonych w pojazdach zgodnie z zaleceniami Ministerstwa Zdrowia</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-2">
                        <p>Motywowanie firm współpracujących z GIGA do wysyłania dokumentów rozliczeniowych i umów drogą elektroniczną</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-3">
                        <p>Prowadzenie rozliczeń bezgotówkowych dla usług wykonywanych oraz otrzymywanych codziennie (bezdotykowe dostawy posiłków na budowę / do biura)</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-4">
                        <p>Wyznaczenie procedur określających zasady postępowania w przypadku pojawienia się osoby z infekcją Covid-19. Określenie zasad zgłoszenia osób, które powinny poddać się kwarantannie.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 pt-5 mt-4">
            <img src="<?=$this->gfxUrl();?>/covid-2.png" alt="Reakcja na COVID">
        </div>
    </div>
</div>