<div class="container">
    <div class="row d-flex justify-content-center text-center">
        <div class="col-8">
            <hr>
        </div>
        <div class="col-12 col-md-10 mb-3 mb-md-5">
            <?=$this->content; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-4">
            <div class="row">
                <div class="col-12">
                    <div class="covid-text ctl-1">
                        <p><?=$this->translate('tl_covid_l_1');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-2">
                        <p><?=$this->translate('tl_covid_l_2');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-3">
                        <p><?=$this->translate('tl_covid_l_3');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-4">
                        <p><?=$this->translate('tl_covid_l_4');?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4 d-flex align-items-center">
            <div class="covid-circle">
                <?=$this->translate('tl_covid_c_1');?>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="row">
                <div class="col-12">
                    <div class="covid-text ctr-1">
                        <p><?=$this->translate('tl_covid_r_1');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-2">
                        <p><?=$this->translate('tl_covid_r_2');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-3">
                        <p><?=$this->translate('tl_covid_r_3');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-4">
                        <p><?=$this->translate('tl_covid_r_4');?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 pt-5 pb-5 mt-4 mb-3">
            <img src="<?=$this->gfxUrl();?>/covid.png" alt="Reakcja na COVID">
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-4">
            <div class="row">
                <div class="col-12">
                    <div class="covid-text ctl-1">
                        <p><?=$this->translate('tl_covid_2_l_1');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-2">
                        <p><?=$this->translate('tl_covid_2_l_2');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-3">
                        <p><?=$this->translate('tl_covid_2_l_3');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctl-4">
                        <p><?=$this->translate('tl_covid_2_l_4');?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4 d-flex align-items-center">
            <div class="covid-circle">
                <?=$this->translate('tl_covid_2_c');?>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="row">
                <div class="col-12">
                    <div class="covid-text ctr-1">
                        <p><?=$this->translate('tl_covid_2_r_1');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-2">
                        <p><?=$this->translate('tl_covid_2_r_2');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-3">
                        <p><?=$this->translate('tl_covid_2_r_3');?></p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="covid-text ctr-4">
                        <p><?=$this->translate('tl_covid_2_r_4');?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 pt-5 mt-4">
            <img src="<?=$this->gfxUrl();?>/covid-2.png" alt="Reakcja na COVID">
        </div>
    </div>
</div>