<div class="container">
    <?=replace($this->strona->tekst); ?>

    <?php foreach($this->inwestycje as $i) { ?>
    <div class="row pt-5 mt-5 giga-invest-row">
        <div class="col-7 pr-4">
            <img src="<?=$this->filesUrl();?>/inwestycje/<?=$this->escape($i->plik);?>" alt="<?=$this->escape($i->nazwa);?>">
        </div>
        <div class="col-5 d-flex align-items-center">
            <div class="giga-invest">
                <h2><?=$this->escape($i->nazwa);?></h2>
                <?=$i->tekst;?>
                <a href="<?=$this->escape($i->link);?>" class="bttn mb-0 mt-3">ZOBACZ STRONĘ WWW</a>
            </div>
        </div>
    </div>
    <?php } ?>
</div>