<div id="kontaktForm">
	<div class="container">
        <div class="contact-shadow">
            <div class="row">
                <div class="col-4 col-text">
                    <h3 class="mt-0">Giga Sp. z o. o.</h3>
                    <p>ul. Cieślewskich 35 K</p>
                    <p>03-017 Warszawa</p>
                    <p>&nbsp;</p>
                    <p>NIP: 113-23-50-424</p>
                    <p>REGON: 017520947</p>
                    <p>&nbsp;</p>
                    <p><a href="tel:+48226145711"><i class="las la-phone-volume"></i> 22 614 57 11</a></p>
                    <p><a href="+48228118225"><i class="las la-phone-volume"></i> 22 811 82 25</a></p>
                    <p><i class="las la-fax"></i> 22 614 57 11 (wew. 102)</p>
                    <p>&nbsp;</p>
                    <p><a href="mailto:sekretariat@giga.waw.pl"><i class="las la-envelope"></i> sekretariat@giga.waw.pl</a></p>
                </div>
                <div class="col-8 col-form">
                    <div class="row">
                        <?php if($this->message == 1) :?>
                        <div id="formalert" class="col-12">
                            <div class="sendok mb-4"><p>Twoja wiadomość została wysłana. W najbliższym czasie skontaktujemy się z Państwem celem omówienia szczegółów!</p></div>
                        </div>
                        <?php endif; ?>
                        <?php if($this->message == 2) :?>
                        <div id="formalert" class="col-12">
                            <div class="senderror mb-4"><p>Uzupełnij wszystkie wymagane pola!</p></div>
                        </div>
                        <?php endif; ?>
                    </div>
                    <form method="post" action="" class="validateForm">
                        <div class="row">
                            <div class="col-12 col-sm-4 col-input mt-2">
                                <label for="form_imie">Imię lub nazwa firmy</label>
                                <input name="imie" id="form_imie" type="text" class="validate[required]" data-prompt-position="topLeft:0" required>
                            </div>
                            <div class="col-12 col-sm-4 col-input mt-2">
                                <label for="form_email">E-mail</label>
                                <input name="email" id="form_email" class="validate[required]" type="text" data-prompt-position="topLeft:0" required>
                            </div>
                            <div class="col-12 col-sm-4 col-input mt-2">
                                <label for="form_telefon">Telefon</label>
                                <input name="telefon" id="form_telefon" class="validate[required]" type="text" data-prompt-position="topLeft:0" required>
                            </div>
                            <div class="col-12 mt-2">
                                <label for="form_wiadomosc">Treść wiadomości</label>
                                <textarea rows="1" cols="1" name="wiadomosc" id="form_wiadomosc"></textarea>
                            </div>
                            <div class="col-12 obowiazek">
                                <?=$this->rodo->obowiazek;?>
                            </div>

                            <div class="col-12">
                                <?php foreach($this->regulki as $regulka){?>
                                    <div class="regulki">
                                        <input
                                        name="zgoda_<?=$regulka->id;?>"
                                        id="zgoda_<?=$regulka->id;?>"
                                        value="1"
                                        type="checkbox"
                                        <?php if($regulka->wymagane == 1){;?>class="validate[required]" required<?php } ?>
                                        data-prompt-position="topLeft:0"
                                        >
                                        <label for="zgoda_<?=$regulka->id;?>" class="rules-text"><?=$regulka->tresc;?></label>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="row row-form-submit">
                            <div class="col-12 text-center">
                                <div class="input">
                                    <script type="text/javascript">
                                        document.write("<button type=\"submit\" class=\"bttn\">WYŚLIJ WIADOMOŚĆ</button>");
                                    </script>
                                    <noscript><p><b>Do poprawnego działania, Java musi być włączona.</b><p></noscript>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
	</div>
</div>
<div id="kontaktMap">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d156041.64177562384!2d21.025747!3d52.331413!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x773ea2494c889554!2sGiga%20Sp.%20z%20o.o.!5e0!3m2!1spl!2spl!4v1613352043343!5m2!1spl!2spl" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</div>
