<div id="kontaktInfo">
	<div class="container">
		<div class="row">
            <div class="col-12 col-md-4">
                <div class="kontakt-card text-center">
                    <span><i class="las la-map-marker-alt"></i></span>
                    <p>90-361 Łódź</p>
                    <p>ul. Piotrkowska 276</p>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="kontakt-card text-center">
                    <span><i class="las la-phone"></i></span>
                    <p>tel. <a href="tel:+48426802762">+48 426 802 762</a></p>
                    <p>tel. <a href="tel:+48506107042">+48 506 107 042</a></p>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="kontakt-card text-center">
                    <span><i class="las la-mail-bulk"></i></span>
                    <p>e-mail:</p>
                    <p><a href="mailto:biuro@jamad-budownictwo.pl">biuro@jamad-budownictwo.pl</a></p>
                </div>
            </div>
		</div>
	</div>
</div>

<div id="kontaktForm" class="darkForm">
	<div class="container">
		<div class="row">
			<div class="col-12 col-form">
				<div class="row">
					<div class="col-12 text-center"><h2 class="underline">Formularz kontaktowy</h2></div>
				</div>
				<div class="row">
					<?php if($this->message == 1) :?>
					<div id="formalert" class="col-12">
						<div class="sendok mb-4"><p>Twoja wiadomość została wysłana. W najbliższym czasie skontaktujemy się z Państwem celem omówienia szczegółów!</p></div>
					</div>
					<?php endif; ?>
					<?php if($this->message == 2) :?>
					<div id="formalert" class="col-12">
						<div class="senderror mb-4"><p>Uzupełnij wszystkie wymagane pola!</p></div>
					</div>
					<?php endif; ?>
				</div>
				<form method="post" action="" class="validateForm">
					<div class="row">
						<div class="col-12 col-sm-4 col-input mt-2">
							<label for="form_imie">Imię lub nazwa firmy</label>
							<input name="imie" id="form_imie" type="text" class="validate[required]" data-prompt-position="topLeft:0" required>
						</div>
						<div class="col-12 col-sm-4 col-input mt-2">
							<label for="form_email">E-mail</label>
							<input name="email" id="form_email" class="validate[required]" type="text" data-prompt-position="topLeft:0" required>
						</div>
						<div class="col-12 col-sm-4 col-input mt-2">
							<label for="form_telefon">Telefon</label>
							<input name="telefon" id="form_telefon" class="validate[required]" type="text" data-prompt-position="topLeft:0" required>
						</div>
						<div class="col-12 mt-2">
							<label for="form_wiadomosc">Treść wiadomości</label>
							<textarea rows="1" cols="1" name="wiadomosc" id="form_wiadomosc"></textarea>
						</div>
						<div class="col-12 obowiazek">
							<?=$this->rodo->obowiazek;?>
						</div>

                        <div class="col-12">
                            <?php foreach($this->regulki as $regulka){?>
                                <div class="regulki">
                                    <input
                                    name="zgoda_<?=$regulka->id;?>"
                                    id="zgoda_<?=$regulka->id;?>"
                                    value="1"
                                    type="checkbox"
                                    <?php if($regulka->wymagane == 1){;?>class="validate[required]" required<?php } ?>
                                    data-prompt-position="topLeft:0"
                                    >
                                    <label for="zgoda_<?=$regulka->id;?>" class="rules-text"><?=$regulka->tresc;?></label>
                                </div>
                            <?php } ?>
                        </div>
					</div>
					<div class="row row-form-submit">
						<div class="col-12 text-center">
							<div class="input">
								<script type="text/javascript">
									document.write("<button type=\"submit\" class=\"bttn\">WYŚLIJ WIADOMOŚĆ</button>");
								</script>
								<noscript><p><b>Do poprawnego działania, Java musi być włączona.</b><p></noscript>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>