<footer>
	<div id="footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col-6 d-flex align-items-center">
                    <div id="flogo">
                        <a href="<?=$this->baseUrl;?>/"><img src="<?=$this->gfxUrl();?>/flogo.png" alt="<?= $this->header->nazwa; ?>"></a>
                    </div>
                </div>
                <div class="col-6 text-right d-flex align-items-center justify-content-end">
                    <div>
                        <p><a href="<?=$this->baseUrl;?>/mapa-strony/">Mapa strony</a></p>
                        <p>Realizacja: <a href="https://www.4dl.pl/" target="_blank">4DL.pl</a></p>
                        <p>Powered by: <a href="https://www.developro.pl/" target="_blank">DeveloPro.pl</a></p>
                    </div>
                </div>
			</div>
		</div>
	</div>
</footer>