<footer>
	<div id="footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12 col-sm-6 d-flex align-items-center justify-content-center justify-content-sm-start">
                    <div id="flogo">
                        <a href="<?=$this->baseUrl;?>/"><img src="<?=$this->gfxUrl();?>/flogo.png" alt="<?= $this->header['nazwa']; ?>"></a>
                    </div>
                </div>
                <div class="col-12 col-sm-6 text-center text-sm-right d-flex align-items-center justify-content-center justify-content-sm-end">
                    <div>
                        <p><a href="<?=$this->baseUrl;?>/<?=$this->lang;?>/mapa-strony/"><?=$this->translate('tl_footer_sitemap');?></a></p>
                        <p><?=$this->translate('tl_footer_realizacja');?>: <a href="https://www.4dl.pl/" target="_blank">4DL.pl</a></p>
                        <p>Powered by: <a href="https://www.developro.pl/" target="_blank">DeveloPro.pl</a></p>
                    </div>
                </div>
			</div>
		</div>
	</div>
</footer>

<div id="backtotop"><i class="las la-angle-double-up"></i></div>