<header class="clearfix">
	<div class="header-holder">
		<div id="header">
			<div class="container-fluid p-0">
				<div class="row no-gutters">
					<div class="col-12">
						<nav class="navbar">
							<ul class="text-center list-unstyled m-0 d-block d-lg-flex w-100 justify-content-start justify-content-lg-center">
								<li class="o-nas-li"><a href="<?=$this->baseUrl;?>/o-nas/" class="animate100<?=$this->activeMenu('o-nas', $this->menutag);?>">O NAS</a>
                                    <ul class="submenu list-unstyled mb-0">
                                        <li><a href="<?=$this->baseUrl;?>/zrownowazony-rozwoj/">ZRÓWNOWAŻONY ROZWÓJ</a></li>
                                    </ul>
                                </li>
								<li><a href="<?=$this->baseUrl;?>/misja-i-wartosci/" class="animate100<?=$this->activeMenu('misja-i-wartosci', $this->menutag);?>">MISJA I WARTOŚCI</a></li>
								<li><a href="<?=$this->baseUrl;?>/realizacje/" class="animate100<?=$this->activeMenu('realizacje', $this->menutag);?>">REALIZACJE</a></li>
                                <li id="logo"><a href="<?=$this->baseUrl;?>/"><img src="<?=$this->gfxUrl();?>/logo.png" alt="<?= $this->header->nazwa; ?>"></a></li>
								<li class="o-nas-li"><a href="<?=$this->baseUrl;?>/oferta/" class="animate100<?=$this->activeMenu('oferta', $this->menutag);?>">OFERTA</a>
                                    <ul class="submenu list-unstyled mb-0">
                                        <li><a href="<?=$this->baseUrl;?>/oferta/giga-development/">GIGA DEVELOPMENT</a></li>
                                        <li><a href="<?=$this->baseUrl;?>/oferta/giga-rental/">GIGA RENTAL</a></li>
                                        <li><a href="<?=$this->baseUrl;?>/oferta/giga-konsorcjum/">GIGA KONSORCJUM</a></li>
                                    </ul>
                                </li>
								<li>
                                    <a href="<?=$this->baseUrl;?>/aktualnosci/" class="animate100<?=$this->activeMenu('aktualnosci', $this->menutag);?>">AKTUALNOŚCI</a>
                                    <ul class="submenu list-unstyled mb-0">
                                        <li><a href="<?=$this->baseUrl;?>/reakcja-na-covid/">Reakcja na COVID</a></li>
                                    </ul>
                                </li>
								<li><a href="<?=$this->baseUrl;?>/kontakt/" class="animate100<?=$this->activeMenu('kontakt', $this->menutag);?>">KONTAKT</a></li>
							</ul>
                            <?php $menu = Zend_Registry::get('querymenu'); //$menu->get_menu_html(0); ?>
						</nav>	
						<div class="mobilemenu"><a href="#" id="triggermenu">MENU</a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<div id="megamenu-opacity"></div>