<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <title><?= $this->main_meta_tytul; ?></title>
    <meta name="description" content="<?= $this->main_meta_opis ?>">
    <meta name="keywords" content="<?= $this->meta_slowa; ?>">
    <?php if($this->header['autor']){?>
        <meta name="author" content="<?= $this->header['autor']; ?>">
    <?php } ?>
    <meta name="robots" content="<?= $this->header['robots']; ?>">

    <link href="favicon.ico" rel="icon" type="image/x-icon">

    <?php if($this->header['share_plik']) {?>
        <meta property="og:title" content="<?= $this->main_meta_tytul; ?>">
        <meta property="og:image" content="<?= $this->header['domena']; ?>files/share/<?=$this->header['share_plik'];?>">
        <meta property="og:description" content="<?=$this->header['share_opis'];?>">
        <meta property="og:type" content="website">
        <meta property="og:image:width" content="600">
        <meta property="og:image:height" content="315">
        <meta property="og:url" content="<?= $this->header['domena']; ?>">
    <?php } ?>

    <!-- Wylaczenie numeru tel. -->
    <meta name="format-detection" content="telephone=no">

    <!-- Prefetch -->
    <link rel="dns-prefetch" href="//fonts.googleapis.com">

    <link rel="stylesheet" href="<?=$this->cssUrl();?>/bootstrap.css">
    <link rel="stylesheet" href="<?=$this->cssUrl();?>/styles.css">
    <style>body,html{height: 100%}</style>
    <?= $this->header['head']; ?>
</head>
<body id="mainpage" class="<?php if(Zend_Auth::getInstance()->hasIdentity()) { ?> is-admin<?php } ?>">

<?=$this->render('header.phtml');?>

<div id="slider" class="clearfix">
    <ul class="rslidess list-unstyled mb-0">
        <?php foreach($this->slider as $panel){?>
            <li>
                <div class="apla">
                    <div>
                        <h3><?php echo (isset($panel->tytul)) ? $panel->tytul : json_decode($panel->json)->tytul;?></h3>
                        <h1><?php echo (isset($panel->tekst)) ? $panel->tekst : json_decode($panel->json)->tekst;?></h1>
                    </div>
                </div>
                <div class="opacity" style="background: rgb(0, 0, 0, <?=$panel->opacity;?>)"></div>
                <img src="<?=$this->filesUrl();?>/slider/<?=$panel->plik;?>" alt="<?=$panel->tytul;?><?php echo (isset($panel->tytul)) ? $panel->tytul : json_decode($panel->json)->tytul;?>">
            </li>
        <?php } ?>
    </ul>
</div>

<div id="welcome">
    <div class="container">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12 col-md-10">
                <h2 class="mt-0" data-modaltytul="1"><?=$this->getInline($this->inline, 1, 'modaltytul');?></h2>
            </div>
            <div class="col-8">
                <hr>
            </div>
            <div class="col-12 col-md-10">
                <p data-modaleditor="1"><?=$this->getInline($this->inline, 1, 'modaleditor');?></p>
            </div>
            <?=$this->inlineModal(1, 'modaltytul,modaleditor');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>
</div>

<div id="mainboxes" class="offerbox">
    <div class="container-fluid p-0">
        <div class="row no-gutters">
            <?php foreach($this->offer as $o){ ?>
                <div class="col-4">
                    <div class="apla d-flex align-items-center justify-content-center">
                        <div class="text-center">
                            <h3 class="m-0"><?php echo (isset($o->nazwa)) ? $o->nazwa : json_decode($o->json)->nazwa;?></h3>
                            <p><?php echo (isset($o->tekst)) ? $o->tekst : json_decode($o->json)->tekst;?></p>
                            <a href="<?php echo (isset($o->link)) ? $o->link : json_decode($o->json)->link;?>" class="bttn mb-0"><?=$this->translate('tl_zobacz_więcej');?></a>
                        </div>
                    </div>
                    <img src="<?=$this->filesUrl();?>/oferta/<?=$this->escape($o->plik);?>" alt="<?php echo (isset($o->nazwa)) ? $o->nazwa : json_decode($o->json)->nazwa;?>">
                </div>
            <?php } ?>
        </div>
    </div>
</div>

<div class="container">
    <div class="row d-flex justify-content-center text-center">
        <div class="col-8">
            <hr>
        </div>
    </div>
</div>

<div id="about">
    <div class="container-fluid">
        <div class="row inline">
            <div class="col-12 col-lg-6 d-flex justify-content-center align-items-center">
                <img src="<?=$this->getInline($this->inline, 2, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 2, 'obrazek_alt');?>" data-img="2">
            </div>
            <div class="col-12 col-lg-6 pl-3 pl-xl-5 d-flex align-items-center">
                <div>
                    <h2 data-modaltytul="2"><?=$this->getInline($this->inline, 2, 'modaltytul');?></h2>
                    <p data-modaleditor="2"><?=$this->getInline($this->inline, 2, 'modaleditor');?></p>
                    <a href="<?=$this->baseUrl;?>/<?=$this->lang;?>/realizacje/" class="bttn mb-0"><?=$this->translate('tl_zobacz_realizacje');?></a>
                </div>
            </div>
            <?=$this->inlineModal(2, 'modaltytul,modaleditor,obrazek,obrazek_alt', '860,600');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>
</div>

<?=$this->render('footer.phtml');?>

<div id="cookies"><p><a href="#" class="closecookies gradient">Zamknij</a><?= $this->header->cookies; ?></p></div>

<!-- jQuery -->
<script src="<?=$this->jsUrl(); ?>/jquery.js" charset="utf-8"></script>
<script src="<?=$this->jsUrl(); ?>/bootstrap.bundle.min.js" charset="utf-8"></script>
<script src="<?=$this->jsUrl(); ?>/main.js" charset="utf-8"></script>

<script type="text/javascript">
    WebFontConfig = {
        google: {
            families: ['Ubuntu:300,400,500,700:latin-ext']
        }
    };

    (function(d) {
        var wf = d.createElement('script'), s = d.scripts[0];
        wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js';
        wf.async = true;
        s.parentNode.insertBefore(wf, s);
    })(document);

    $(document).ready(function(){
        $(".rslidess").responsiveSlides({auto:<?=$this->slider_ustawienia->slider_auto; ?>, pager:false, nav:<?=$this->slider_ustawienia->slider_nav; ?>, timeout:<?=$this->slider_ustawienia->slider_timeout; ?>, random:false, speed: <?=$this->slider_ustawienia->slider_speed; ?>});

        <?php if($this->header['popup_status'] == 1){; ?>
        <?php if($this->header['popup_tryb'] == 1){; ?>
        $.cookie('popup', null);
        $.magnificPopup.open({
            items: {
                src: '<div class="white-popup"><?= str_replace (array("\r\n", "\n", "\r"), ' ', $this->header['popup_tekst']); ?></div>',
                type: 'inline'
            }
        });
        setTimeout( function(){
            $.magnificPopup.close();
        }, 5000 );
        <?php } else {?>
        if ($.cookie('popup') == null){
            $.magnificPopup.open({
                items: {
                    src: '<div class="white-popup"><?= str_replace (array("\r\n", "\n", "\r"), ' ', $this->header['popup_tekst']); ?></div>',
                    type: 'inline'
                }
            });
            setTimeout( function(){
                $.magnificPopup.close();
            }, 5000 );
            $.cookie('popup','true');
        }
        <?php } ?>
        <?php } else {?>
        $.cookie('popup', null);
        <?php } ?>
    });
</script>
<?= $this->header['footer']; ?>

<?php if(Zend_Auth::getInstance()->hasIdentity()){?>
    <?=$this->render('inline/inline.phtml') ?>
<?php } ?>
</body>
</html>