<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <title><?= $this->header->nazwa; ?></title>
    <meta name="description" content="<?= $this->header->opis ?>">
    <meta name="keywords" content="<?= $this->header->klucze; ?>">
    <?php if($this->header->autor){?>
        <meta name="author" content="<?= $this->header->autor; ?>">
    <?php } ?>
    <meta name="robots" content="<?= $this->header->robots; ?>">

    <link href="favicon.ico" rel="icon" type="image/x-icon">

    <?php if($this->header->share_plik) {?>
        <meta property="og:title" content="<?=$this->header->share_tytul;?>">
        <meta property="og:image" content="<?= $this->header->domena; ?>files/share/<?=$this->header->share_plik;?>">
        <meta property="og:description" content="<?=$this->header->share_opis;?>">
        <meta property="og:type" content="website">
        <meta property="og:image:width" content="600">
        <meta property="og:image:height" content="315">
        <meta property="og:url" content="<?= $this->header->domena; ?>">
    <?php } ?>

    <!-- Wylaczenie numeru tel. -->
    <meta name="format-detection" content="telephone=no">

    <!-- Prefetch -->
    <link rel="dns-prefetch" href="//fonts.googleapis.com">

    <link rel="stylesheet" href="<?=$this->cssUrl();?>/bootstrap.css">
    <link rel="stylesheet" href="<?=$this->cssUrl();?>/styles.css">
    <style>body,html{height: 100%}</style>
    <?= $this->header->head; ?>
</head>
<body id="mainpage">

<?=$this->render('header.phtml');?>

<div id="slider" class="clearfix">
    <ul class="rslidess list-unstyled mb-0">
        <?php foreach($this->slider as $panel){?>
            <li>
                <div class="apla">
                    <div>
                        <h3><?=$panel->tekst;?></h3>
                        <h1><?=$panel->tytul;?></h1>
                    </div>
                </div>
                <div class="opacity" style="background: rgb(0, 0, 0, <?=$panel->opacity;?>)"></div>
                <img src="<?=$this->filesUrl();?>/slider/<?=$panel->plik;?>" alt="<?=$panel->tytul;?>">
            </li>
        <?php } ?>
    </ul>
</div>

<div id="welcome">
    <div class="container">
        <div class="row d-flex justify-content-center text-center">
            <div class="col-10">
                <h2 class="mt-0">Od pierwszego dnia istnienia <b>GIGA</b> działa jako most łączący inwestorów oraz firmy budowlane w formie generalnego wykonawcy.</h2>
            </div>
            <div class="col-8">
                <hr>
            </div>
            <div class="col-10">
                <p>Szeroki wachlarz usług począwszy od planowania i projektowania a kończąc na wykonawstwie i wdrożeniu w produkcję. GIGA od ponad 20 lat kreatywnie oraz z zachowaniem najwyższej staranności wyznacza trendy w budownictwie stale inspirując partnerów do wspólnego rozwoju. Podejmowanym działaniom towarzyszy zawsze poczucie odpowiedzialności za lokalne społeczności oraz środowisko.</p>
            </div>
        </div>
    </div>
</div>

<div id="mainboxes">
    <div class="container-fluid p-0">
        <div class="row no-gutters">
            <div class="col-4">
                <div class="apla d-flex align-items-center justify-content-center">
                    <div class="text-center">
                        <h3 class="m-0">O nas</h3>
                        <p>Aliquam vel scelerisque nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum quis est metus. In hac habitasse platea dictumst.</p>
                        <a href="" class="bttn mb-0">ZOBACZ WIĘCEJ</a>
                    </div>
                </div>
                <img src="https://via.placeholder.com/850x500" alt="">
            </div>
            <div class="col-4">
                <div class="apla d-flex align-items-center justify-content-center">
                    <div class="text-center">
                        <h3 class="m-0">Misja i wartości</h3>
                        <p>Aliquam vel scelerisque nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum quis est metus. In hac habitasse platea dictumst.</p>
                        <a href="" class="bttn mb-0">ZOBACZ WIĘCEJ</a>
                    </div>
                </div>
                <img src="https://via.placeholder.com/850x500" alt="">
            </div>
            <div class="col-4">
                <div class="apla d-flex align-items-center justify-content-center">
                    <div class="text-center">
                        <h3 class="m-0">Realizacje</h3>
                        <p>Aliquam vel scelerisque nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum quis est metus. In hac habitasse platea dictumst.</p>
                        <a href="" class="bttn mb-0">ZOBACZ WIĘCEJ</a>
                    </div>
                </div>
                <img src="https://via.placeholder.com/850x500" alt="">
            </div>
            <div class="col-4">
                <div class="apla d-flex align-items-center justify-content-center">
                    <div class="text-center">
                        <h3 class="m-0">Zrównoważony Rozwój</h3>
                        <p>Aliquam vel scelerisque nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum quis est metus. In hac habitasse platea dictumst.</p>
                        <a href="" class="bttn mb-0">ZOBACZ WIĘCEJ</a>
                    </div>
                </div>
                <img src="https://via.placeholder.com/850x500" alt="">
            </div>
            <div class="col-4">
                <div class="apla d-flex align-items-center justify-content-center">
                    <div class="text-center">
                        <h3 class="m-0">Oferta</h3>
                        <p>Aliquam vel scelerisque nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum quis est metus. In hac habitasse platea dictumst.</p>
                        <a href="" class="bttn mb-0">ZOBACZ WIĘCEJ</a>
                    </div>
                </div>
                <img src="https://via.placeholder.com/850x500" alt="">
            </div>
            <div class="col-4">
                <div class="apla d-flex align-items-center justify-content-center">
                    <div class="text-center">
                        <h3 class="m-0">Aktualności</h3>
                        <p>Aliquam vel scelerisque nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum quis est metus. In hac habitasse platea dictumst.</p>
                        <a href="" class="bttn mb-0">ZOBACZ WIĘCEJ</a>
                    </div>
                </div>
                <img src="https://via.placeholder.com/850x500" alt="">
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row d-flex justify-content-center text-center">
        <div class="col-8">
            <hr>
        </div>
    </div>
</div>

<div id="about">
    <div class="container-fluid">
        <div class="row">
            <div class="col-6 d-flex justify-content-center align-items-center">
                <img src="<?=$this->filesUrl();?>/upload/about.jpg" alt="O nas">
            </div>
            <div class="col-6 pl-5 d-flex align-items-center">
                <div>
                    <h2>Budownictwo polega nie tylko na wznoszeniu nowych konstrukcji, <b>budowanie to także dążenie do osiągania trwałych oraz wartościowych relacji międzyludzkich pomagających tworzyć lepsze jutro</b>.</h2>
                    <p>Integer aliquam tincidunt vulputate. Curabitur efficitur quis ante in vestibulum. Donec aliquam felis purus, vitae scelerisque sem gravida ac. Nulla facilisi. Aenean id orci a elit volutpat auctor. Sed iaculis purus vitae lectus rutrum tristique. Proin fermentum venenatis ultricies.</p>
                    <a href="" class="bttn mb-0">ZOBACZ WIĘCEJ</a>
                </div>
            </div>
        </div>
    </div>
</div>

<?=$this->render('footer.phtml');?>

<div id="cookies"><p><a href="#" class="closecookies gradient">Zamknij</a><?= $this->header->cookies; ?></p></div>

<!-- jQuery -->
<script src="<?=$this->jsUrl(); ?>/jquery.js" charset="utf-8"></script>
<script src="<?=$this->jsUrl(); ?>/bootstrap.bundle.min.js" charset="utf-8"></script>
<script src="<?=$this->jsUrl(); ?>/main.js" charset="utf-8"></script>

<script type="text/javascript">
    WebFontConfig = {
        google: {
            families: ['Ubuntu:300,400,500,700:latin-ext']
        }
    };

    (function(d) {
        var wf = d.createElement('script'), s = d.scripts[0];
        wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js';
        wf.async = true;
        s.parentNode.insertBefore(wf, s);
    })(document);

    $(document).ready(function(){
        $(".rslidess").responsiveSlides({auto:true, pager:false, nav:true, timeout:8000, random:false, speed: 300});

        <?php if($this->header->popup_status == 1){; ?>
        <?php if($this->header->popup_tryb == 1){; ?>
        $.cookie('popup', null);
        $.magnificPopup.open({
            items: {
                src: '<div class="white-popup"><?= str_replace (array("\r\n", "\n", "\r"), ' ', $this->header->popup_tekst); ?></div>',
                type: 'inline'
            }
        });
        setTimeout( function(){
            $.magnificPopup.close();
        }, 5000 );
        <?php } else {?>
        if ($.cookie('popup') == null){
            $.magnificPopup.open({
                items: {
                    src: '<div class="white-popup"><?= str_replace (array("\r\n", "\n", "\r"), ' ', $this->header->popup_tekst); ?></div>',
                    type: 'inline'
                }
            });
            setTimeout( function(){
                $.magnificPopup.close();
            }, 5000 );
            $.cookie('popup','true');
        }
        <?php } ?>
        <?php } else {?>
        $.cookie('popup', null);
        <?php } ?>
    });
</script>
<?= $this->header->footer; ?>
</body>
</html>