<div class="container">
    <div class="row">
        <div class="col-12 pb-4">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras finibus finibus laoreet. Vestibulum id libero mi. Donec eget dolor leo. Vivamus vulputate malesuada gravida. Nulla luctus nisi lacinia leo pellentesque blandit. Duis nisl mauris, dictum vel mauris a, condimentum pulvinar tellus. Proin ac ultricies ligula. Aliquam commodo eleifend velit id tempus. Nam sollicitudin egestas justo ac malesuada. Suspendisse vitae efficitur metus. Proin dapibus elit quis purus placerat pharetra. Mauris ac nunc eget eros placerat lobortis et in leo. </p>
        </div>
    </div>
    <?=replace('[galeria=galeria]1[/galeria]'); ?>
</div>