<div class="container-fluid">
    <div class="row d-flex justify-content-center text-center">
        <div class="col-12 text-center projects-filter">
            <a href="">Wszystkie</a><span>/</span><a href="">Użyteczności publicznej</a><span>/</span><a href="">Przemysłowe</a>
        </div>
        <div class="col-8">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <a href="">
                <div class="project-item">
                    <img src="<?=$this->filesUrl();?>/realizacje/1.jpg" alt="">
                    <div class="project-overlay">
                        <div class="project-content">
                            <div class="icon">
                                <i class="las la-plus-circle"></i>
                            </div>
                            <div class="content">
                                <h4>Nazwa inwestycji</h4>
                                <p class="p-name">Miasto</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-3">
            <a href="">
                <div class="project-item">
                    <img src="<?=$this->filesUrl();?>/realizacje/1.jpg" alt="">
                    <div class="project-overlay">
                        <div class="project-content">
                            <div class="icon">
                                <i class="las la-plus-circle"></i>
                            </div>
                            <div class="content">
                                <h4>Nazwa inwestycji</h4>
                                <p class="p-name">Miasto</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-3">
            <a href="">
                <div class="project-item">
                    <img src="<?=$this->filesUrl();?>/realizacje/1.jpg" alt="">
                    <div class="project-overlay">
                        <div class="project-content">
                            <div class="icon">
                                <i class="las la-plus-circle"></i>
                            </div>
                            <div class="content">
                                <h4>Nazwa inwestycji</h4>
                                <p class="p-name">Miasto</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-3">
            <a href="">
                <div class="project-item">
                    <img src="<?=$this->filesUrl();?>/realizacje/1.jpg" alt="">
                    <div class="project-overlay">
                        <div class="project-content">
                            <div class="icon">
                                <i class="las la-plus-circle"></i>
                            </div>
                            <div class="content">
                                <h4>Nazwa inwestycji</h4>
                                <p class="p-name">Miasto</p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>