<div class="container">
    <div class="row">
        <div class="col-12 news-post">
            <article id="post-<?=$this->news->id;?>" itemscope itemType="http://schema.org/BlogPosting">
                <h1 class="mt-4 mb-4"><a href="<?=$this->baseUrl;?>/realizacja/<?=$this->news->slug;?>/" title="<?php echo (isset($this->news->nazwa)) ? $this->news->nazwa : json_decode($this->news->json)->nazwa;?>" itemprop="url"><span itemprop="name headline"><?php echo (isset($this->news->nazwa)) ? $this->news->nazwa : json_decode($this->news->json)->nazwa;?></span></a></h1>
                <div itemprop="articleBody">
                    <?php echo (isset($this->news->tekst)) ? replace($this->news->tekst) : replace(json_decode($this->news->json)->tekst);?>
                </div>
            </article>
        </div>
    </div>
</div>